// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointCoverage } from "./CheckpointCoverage.js";
import type { CheckpointSafeOptions } from "./CheckpointSafeOptions.js";
import type { CheckpointSkippedBinding } from "./CheckpointSkippedBinding.js";

export type CheckpointNativeReport = { saved_names: Array<string>, skipped: Array<CheckpointSkippedBinding>, r_version: string, platform: string, library_paths: Array<string>, package_inventory_digest: string, working_directory: string | null, safe_options: CheckpointSafeOptions, context_notices: Array<string>, required_core_namespaces: Array<string>, required_class_namespaces: Array<string>, coverage: CheckpointCoverage, };
