// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckpointSafeOptions = { digits: number | null, width: number | null, scipen: number | null, out_dec: string | null, warn: number | null, };
