// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckpointNativeRestoreReport = { restored_names: Array<string>, initialized_namespaces: Array<string>, notices: Array<string>, };
