// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputRequest } from "./InputRequest.js";
import type { QueuePause } from "./QueuePause.js";
import type { QueuedRun } from "./QueuedRun.js";

export type ConsoleState = { session_id: string, current: QueuedRun | null, pending: Array<QueuedRun>, pause: QueuePause | null, input: InputRequest | null, };
