// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { REnvironmentSelection } from "./REnvironmentSelection.js";

export type CreateRSession = { environment: REnvironmentSelection, };
