// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { OperationId } from "./OperationId.js";

export type DiscardRCapture = { source_operation_id: OperationId, expected_fingerprint: ContentDigest, };
