// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunRArguments } from "./RunRArguments.js";

export type ExecuteR = { expected_session: string, run: RunRArguments, };
