// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunSource } from "./RunSource.js";

/**
 * An explicit code-tool Operation in an already selected native session.
 * Formatting parses text; it does not evaluate it or write a project file.
 */
export type FormatRCode = { expected_session: string, code: string, source: RunSource | null, };
