// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rendering format. HTML is produced by the static `tools::Rd2HTML` stage and is
 * suitable for a sanitized document view; text remains the bounded default.
 */
export type HelpFormat = "text" | "html";
