// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";

export type InputRequest = { session_id: string, operation_id: OperationId, request_id: string, prompt: string, password: boolean, submitted: boolean, };
