// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InspectArguments = { name: string, max_items: number, expected_session: string | null, };
