// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectMetadata } from "./ObjectMetadata.js";

export type ObjectChild = { index: number, name: string | null, metadata: ObjectMetadata, };
