// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObjectReadKind = "structure" | "values" | "children" | "table" | "text" | "levels" | "names";
