// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { OutputEvent } from "./OutputEvent.js";

export type OutputEvents = { operation_id: OperationId, events: Array<OutputEvent>, next_sequence: number, has_more: boolean, truncated: boolean, gap: boolean, notices: Array<string>, };
