// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaReference } from "./MediaReference.js";
import type { OperationId } from "./OperationId.js";

export type OutputEvent = { operation_id: OperationId, sequence: number, kind: string, text: string | null, media: MediaReference | null, observed_at_ms: number, };
