// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageProjectLink } from "./PackageProjectLink.js";
import type { PackageSourceField } from "./PackageSourceField.js";

export type PackageSource = { kind: string, repository: string | null, repository_url: string | null, remote_host: string | null, remote_ref: string | null, remote_sha: string | null, delivery_url: string | null, provider: string | null, snapshot: string | null, evidence: Array<PackageSourceField>, links: Array<PackageProjectLink>, notice: string | null, };
