// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageDescriptionField } from "./PackageDescriptionField.js";
import type { PackageFileIdentity } from "./PackageFileIdentity.js";
import type { PackageIndexEntry } from "./PackageIndexEntry.js";

export type PackageIndexPage = { index_ref: string, observation_id: string, package: string, library_path: string, version: string, files: Array<PackageFileIdentity>, description: Array<PackageDescriptionField>, entries: Array<PackageIndexEntry>, total: number, offset: number, next_offset: number | null, observed_at_ms: number, complete: boolean, notices: Array<string>, };
