// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageQueryMode } from "./PackageQueryMode.js";

/**
 * Bounded observation of the libraries and namespaces of the existing R session.
 */
export type PackageQueryArguments = { expected_session: string | null, filter: string, mode: PackageQueryMode, grouped: boolean, observation_id: string | null, package_name: string | null, offset: number, limit: number, };
