// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageIndexArguments = { expected_session: string, observation_id: string, package: string, library_path: string, index_ref: string | null, filter: string, kind: string | null, offset: number, limit: number, };
