// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageCounts } from "./PackageCounts.js";
import type { PackageEntry } from "./PackageEntry.js";
import type { PackageGroup } from "./PackageGroup.js";
import type { PackageLibrary } from "./PackageLibrary.js";
import type { PackageQueryMode } from "./PackageQueryMode.js";

export type PackageSnapshotData = { r_version: string, r_home: string, platform: string, library_paths: Array<string>, mode: PackageQueryMode, filter: string, offset: number, next_offset: number | null, packages: Array<PackageEntry>, groups: Array<PackageGroup>, counts: PackageCounts, libraries: Array<PackageLibrary>, observation_id: string, observed_at_ms: number, package_name: string | null, total_matches: number, scanned: number, scan_complete: boolean, notices: Array<string>, };
