// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageGroup = { name: string, title: string | null, version: string, first_version: string | null, primary_library_path: string | null, copy_count: number, loaded_version: string | null, loaded_path: string | null, loaded_copy_observed: boolean, attached: boolean, source_kind: string, source_count: number, };
