// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageCounts = { all: number, installed: number, installations: number, loaded: number, attached: number, multiple: number, };
