// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RunSource } from "./RunSource.js";

export type QueuedRun = { operation_id: OperationId, source: RunSource | null, summary: string, };
