// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";

export type QueueControlArguments = { session_id: string, pause_id: string | null,
/**
 * Optional atomic resume fence: the failed pause and every queued/current run
 * must belong to this explicit set. It cannot authorize resuming hidden work.
 */
only_operation_ids?: Array<OperationId>, };
