// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RCaptureAttemptReference } from "./RCaptureAttemptReference.js";
import type { RCaptureMaterial } from "./RCaptureMaterial.js";

export type RCaptureDiscarded = { operation_id: OperationId, reference: RCaptureAttemptReference, before: RCaptureMaterial, after: RCaptureMaterial, };
