// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { PluginOutcome } from "./PluginOutcome.js";
import type { RCaptureAttemptReference } from "./RCaptureAttemptReference.js";
import type { RCaptureMaterial } from "./RCaptureMaterial.js";

export type RCaptureAttemptObservation = { reference: RCaptureAttemptReference, original_status: PluginOutcome, material: RCaptureMaterial, owner_released: boolean, can_discard: boolean, discarded_by: OperationId | null, notices: Array<string>, };
