// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceRef } from "./InstanceRef.js";
import type { OperationId } from "./OperationId.js";
import type { ProjectId } from "./ProjectId.js";

/**
 * An attempted capture can lack complete payload metadata. Its original Core
 * operation and provider establish identity without inventing a payload digest.
 */
export type RCaptureAttemptReference = { project: ProjectId, provider: InstanceRef, operation_id: OperationId, };
