// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";

export type RCaptureMaterial = {
/**
 * Opaque native identity/metadata precondition, not a payload content hash.
 */
fingerprint: ContentDigest, payload_bytes: number | null, staging_bytes: number | null,
/**
 * Bounded capture metadata parsed successfully; payload integrity is separate.
 */
capture_metadata_available: boolean, };
