// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RCheckpointReference } from "./RCheckpointReference.js";

export type RCheckpointRead = { reference: RCheckpointReference, offset: number, limit: number, };
