// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RCheckpointControlResult } from "./RCheckpointControlResult.js";
import type { RExecutionNotStarted } from "./RExecutionNotStarted.js";

export type RCheckpointControlOutput = RCheckpointControlResult | RExecutionNotStarted;
