// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RCheckpointLibraries = { library_paths: Array<string>, namespace_paths: Array<string>,
/**
 * False retains unknown dependencies; an empty list cannot imply absence.
 */
complete: boolean, };
