// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { PluginOutcome } from "./PluginOutcome.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";

export type RCheckpointControlObservation = { operation_id: OperationId, reference: RCheckpointReference, status: PluginOutcome, source_operation_id: OperationId, latest_attempt: OperationId | null,
/**
 * A new committed resolution; the original outcome is never rewritten.
 */
resolution: OperationId | null, can_resolve: boolean, can_apply: boolean, notices: Array<string>, };
