// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RCheckpointPayloadState } from "./RCheckpointPayloadState.js";
import type { RCheckpointResult } from "./RCheckpointResult.js";

export type RCheckpointObservation = { checkpoint: RCheckpointResult, control_head: OperationId | null, pinned: boolean, deleted: boolean, payload: RCheckpointPayloadState, notices: Array<string>, };
