// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointNativeReport } from "./CheckpointNativeReport.js";
import type { RCheckpointLibraries } from "./RCheckpointLibraries.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";
import type { RSessionEnvironment } from "./RSessionEnvironment.js";

export type RCheckpointManifest = { reference: RCheckpointReference, native_session_id: string, report: CheckpointNativeReport, environment: RSessionEnvironment | null, libraries: RCheckpointLibraries, source: RCheckpointReference | null, };
