// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RCheckpointControlResolution } from "./RCheckpointControlResolution.js";
import type { RExecutionNotStarted } from "./RExecutionNotStarted.js";

export type RCheckpointControlResolutionOutput = RCheckpointControlResolution | RExecutionNotStarted;
