// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RCheckpointRestored } from "./RCheckpointRestored.js";
import type { RExecutionNotStarted } from "./RExecutionNotStarted.js";

export type RCheckpointRestoreOutput = RCheckpointRestored | RExecutionNotStarted;
