// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RCheckpointResult } from "./RCheckpointResult.js";

export type RCheckpointPage = {
/**
 * Successful original capture/reconciliation results in this bounded journal
 * page. Inspect each exact reference for current pin/deletion/native state.
 */
checkpoints: Array<RCheckpointResult>, next_cursor: number | null, };
