// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RCheckpointResult } from "./RCheckpointResult.js";
import type { RExecutionNotStarted } from "./RExecutionNotStarted.js";

export type RCheckpointCaptureOutput = RCheckpointResult | RExecutionNotStarted;
