// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointCoverage } from "./CheckpointCoverage.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";
import type { ResourceReference } from "./ResourceReference.js";

export type RCheckpointResult = { reference: RCheckpointReference, manifest: ResourceReference, native_session_id: string, saved_count: number, skipped_count: number, coverage: CheckpointCoverage, };
