// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";

export type RCheckpointPurged = { operation_id: OperationId, reference: RCheckpointReference, payload_removed: true, };
