// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RCheckpointControlDecision } from "./RCheckpointControlDecision.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";

export type RCheckpointControlResolution = { operation_id: OperationId, reference: RCheckpointReference, source_operation_id: OperationId, previous_attempt: OperationId | null, decision: RCheckpointControlDecision, pinned: boolean, deleted: boolean, };
