// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { InstanceRef } from "./InstanceRef.js";
import type { OperationId } from "./OperationId.js";
import type { ProjectId } from "./ProjectId.js";

export type RCheckpointReference = { project: ProjectId, provider: InstanceRef, operation_id: OperationId, digest: ContentDigest, bytes: number, };
