// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";

export type RCheckpointControlResult = { operation_id: OperationId, reference: RCheckpointReference, pinned: boolean,
/**
 * Logical retirement is committed by the core. This does not claim that
 * the post-commit disk cleanup has completed; observe the original copy.
 */
deleted: boolean, };
