// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HelpFormat } from "./HelpFormat.js";
import type { PackageFileIdentity } from "./PackageFileIdentity.js";

export type ReadPackageHelpArguments = { expected_session: string, observation_id: string, package: string, library_path: string, topic: string, expected_index_files: Array<PackageFileIdentity>, expected_help_files: Array<PackageFileIdentity> | null, offset_utf8: number, limit_bytes: number, format: HelpFormat, };
