// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";

export type ReadREvents = { expected_session: string, operation_id: OperationId, after_sequence: number, limit: number, };
