// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { ProviderBinding } from "./ProviderBinding.js";

/**
 * Exact Environment provider and original successful realization. Selecting it
 * does not start R; creation performs explicit verification under this binding.
 */
export type REnvironmentSelection = { binding: ProviderBinding, realization: OperationId, };
