// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RCheckpointControlDecision } from "./RCheckpointControlDecision.js";
import type { RCheckpointReference } from "./RCheckpointReference.js";

/**
 * Version 2 of pin/delete resolves one terminal version-1 request. Version 1
 * readers reject that control version instead of silently ignoring a new fact.
 */
export type ResolveRCheckpointControl = { reference: RCheckpointReference, source_operation_id: OperationId, expected_attempt: OperationId | null, decision: RCheckpointControlDecision, };
