// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaReference } from "./MediaReference.js";
import type { ResourceReference } from "./ResourceReference.js";

export type RetainedROutput = { native: MediaReference, reference: ResourceReference, };
