// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputEvents } from "./OutputEvents.js";

export type REventsObservation = { session_id: string, output: OutputEvents, };
