// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { ResourceReference } from "./ResourceReference.js";
import type { RetainedROutput } from "./RetainedROutput.js";
import type { RunROutputMode } from "./RunROutputMode.js";
import type { RunSource } from "./RunSource.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type RExecutionResult = { operation_id: OperationId, session_id: string,
/**
 * R's dynamic value; larger values remain in the full retained report.
 */
value: JsonValue, value_in_report: boolean, stdout: string, stderr: string, report: ResourceReference, events: ResourceReference, outputs: Array<RetainedROutput>, source: RunSource | null, output_mode: RunROutputMode | null, };
