// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RExecutionNotStarted } from "./RExecutionNotStarted.js";
import type { RExecutionResult } from "./RExecutionResult.js";

export type RExecutionOutput = RExecutionResult | RExecutionNotStarted;
