// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeCompleteness } from "./NativeCompleteness.js";
import type { RInspectionDiagnostic } from "./RInspectionDiagnostic.js";
import type { RInspectionStatus } from "./RInspectionStatus.js";

/**
 * A successful RPC can report a busy or unavailable native observation. No
 * cached value is presented as current, and continuation errors keep their code.
 */
export type RInspection<T> = { session_id: string, status: RInspectionStatus, source: string, observed_at_ms: number, completeness: NativeCompleteness, data: T | null, notices: Array<string>, diagnostic: RInspectionDiagnostic | null, };
