// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RInspectionStatus } from "./RInspectionStatus.js";

/**
 * A cheap observation of this R owner's inspection readiness. The cache key is
 * scoped to the exact instance and session. It invalidates presentation caches,
 * never serves as a scientific precondition or establishes an Operation outcome.
 */
export type RInspectionState = { session_id: string | null, status: RInspectionStatus,
/**
 * Changes before and after native execution, even if polling misses the run.
 * Read-only inspections do not change it. None means no session exists.
 */
cache_key: string | null, observed_at_ms: number, notices: Array<string>, };
