// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RInspectionStateArguments = {
/**
 * Null observes an unstarted instance; a supplied session must match exactly.
 */
expected_session: string | null, };
