// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RSessionEnvironment } from "./RSessionEnvironment.js";
import type { RuntimeInstallationIdentity } from "./RuntimeInstallationIdentity.js";
import type { RuntimeProcessIdentity } from "./RuntimeProcessIdentity.js";

export type RSessionCreated = { operation_id: OperationId, session_id: string, process: RuntimeProcessIdentity | null, installation: RuntimeInstallationIdentity | null, project_root: string, environment: RSessionEnvironment | null, };
