// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { OperationId } from "./OperationId.js";
import type { ProviderBinding } from "./ProviderBinding.js";
import type { REnvironmentSelection } from "./REnvironmentSelection.js";
import type { ResourceReference } from "./ResourceReference.js";

export type RSessionEnvironment = { selection: REnvironmentSelection, source: ProviderBinding, report: ResourceReference, verification: OperationId, verification_report: ResourceReference, library_path: string, library_digest: ContentDigest, };
