// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunROutputMode } from "./RunROutputMode.js";
import type { RunSource } from "./RunSource.js";

export type RunRArguments = { code: string, output_mode?: RunROutputMode | null, source?: RunSource | null, };
