// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { AgentHandoffQuery } from "./AgentHandoffQuery.js";

export type AgentHandoffsQuery = { project_root: string, window: AgentControllerRef, query: AgentHandoffQuery, };
