// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHandoffReceipt } from "./AgentHandoffReceipt.js";
import type { AgentHandoffSourceSnapshot } from "./AgentHandoffSourceSnapshot.js";
import type { AgentHandoffTargetSnapshot } from "./AgentHandoffTargetSnapshot.js";

export type AgentHandoffQueryResult = { "kind": "source", source: AgentHandoffSourceSnapshot, } | { "kind": "target", target: AgentHandoffTargetSnapshot, } | { "kind": "receipt", receipt: AgentHandoffReceipt | null, };
