// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { AgentDecision } from "./AgentDecision.js";
import type { AgentNativeCapabilities } from "./AgentNativeCapabilities.js";

export type AgentAttachment = { generation: number, controller: AgentControllerRef, connection_id: string | null, state: string, capabilities: AgentNativeCapabilities, decisions: Array<AgentDecision>, error: string | null, control_frozen: boolean, };
