// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskControl } from "./AgentTaskControl.js";
import type { ResourceReference } from "./ResourceReference.js";

export type AgentResourceAssetUpload = { request_id: string, control: AgentTaskControl, name: string, reference: ResourceReference, };
