// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAsset } from "./AgentAsset.js";
import type { AgentCommandReceipt } from "./AgentCommandReceipt.js";
import type { AgentTaskDraft } from "./AgentTaskDraft.js";
import type { AgentTaskSummary } from "./AgentTaskSummary.js";

export type AgentTaskDetail = { summary: AgentTaskSummary, draft: AgentTaskDraft, assets: Array<AgentAsset>, receipts: Array<AgentCommandReceipt>, };
