// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProvider } from "./AgentProvider.js";

export type AgentDiagnostic = { request_id: string, provider: AgentProvider, model: string, state: string, elapsed_ms: number | null, response: string | null, error: string | null, };
