// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentNativeToolKind } from "./AgentNativeToolKind.js";
import type { AgentNativeToolSelection } from "./AgentNativeToolSelection.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Descriptions, schemas and scopes are captured from the selected immutable
 * plugin manifest or native Host contract, never supplied by model tool arguments.
 */
export type AgentNativeToolGrant = { selection: AgentNativeToolSelection, kind: AgentNativeToolKind, description: string, input_schema: JsonValue, required_scopes: Array<string>, };
