// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentNativeToolTarget } from "./AgentNativeToolTarget.js";

export type AgentNativeToolSelection = { name: string, target: AgentNativeToolTarget, };
