// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { ProjectAgentTaskRef } from "./ProjectAgentTaskRef.js";

export type AgentHandoffSourceSnapshot = { source: ProjectAgentTaskRef, title: string, body: string, context: Array<AgentContextSelection>, revision: string, truncated: boolean, notices: Array<string>, };
