// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDraftContent } from "./AgentDraftContent.js";

export type AgentTaskDraft = { version: number, content: AgentDraftContent, updated_at_ms: number, };
