// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProvider } from "./AgentProvider.js";

export type AgentTask = { task_id: string, project_root: string, provider: AgentProvider, native_session_id: string | null, title: string, created_at_ms: number, updated_at_ms: number, archived: boolean, model: string, effort: string | null, mode: string | null, };
