// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTaskEvent } from "./AgentTaskEvent.js";

export type AgentNativeHistoryPage = { task_id: string, events: Array<AgentTaskEvent>, next_cursor: string | null, source: string, partial: boolean, };
