// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAgentBudget } from "./ComponentAgentBudget.js";
import type { ComponentAgentProfile } from "./ComponentAgentProfile.js";
import type { ComponentAgentTaskIntent } from "./ComponentAgentTaskIntent.js";
import type { ComponentModelConnection } from "./ComponentModelConnection.js";
import type { ComponentPermissionPolicy } from "./ComponentPermissionPolicy.js";

/**
 * Data captured by the task owner before entering a model engine. No live owner
 * record, tool credentials or scientific operation flow is exposed to the engine.
 */
export type AgentModelRun = { run_id: string, profile: ComponentAgentProfile, model: ComponentModelConnection, budget: ComponentAgentBudget, created_at_ms: number, text: string, permission_policy: ComponentPermissionPolicy | null, task_intent: ComponentAgentTaskIntent | null, };
