// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Correlation identity supplied by the Agent owner after admission. This value
 * is not an authorization credential and cannot grant access to a Host window.
 */
export type AgentControllerRef = { window_id: string, incarnation: string, };
