// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentModel } from "./AgentModel.js";
import type { AgentPermissionMode } from "./AgentPermissionMode.js";

export type AgentNativeCapabilities = { resume: boolean, history: string, images: boolean, embedded_context: boolean, modes: Array<AgentPermissionMode>, current_mode: string | null, models: Array<AgentModel>, };
