// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { PluginRequest } from "./PluginRequest.js";
import type { ProjectId } from "./ProjectId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type AgentNativeToolRequest = { "type": "provider", request: PluginRequest, } | { "type": "host", project: ProjectId, capability: CapabilityKey,
/**
 * Complete native input, including the caller's captured fields.
 */
arguments: JsonValue, };
