// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

export type AgentNativeToolInvocation = {
/**
 * Explicit original Send identity prevents a stale native tool call from
 * becoming new work merely because the same connection has another turn.
 */
send_request: string, tool_request: string, tool: string, arguments: JsonValue, preconditions: JsonValue, };
