// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { AgentDraftContent } from "./AgentDraftContent.js";

export type AgentCommandReceipt = { request_id: string, task_id: string, command: string, input_digest: string, request_digest: string, input_assets: Array<string>, input_context: Array<AgentContextSelection>,
/**
 * Recovery material retained until native completion is confirmed.
 */
submitted_draft: AgentDraftContent | null, status: string, native_session_id: string | null, native_turn_id: string | null, created_at_ms: number, updated_at_ms: number, error: string | null, submitted_draft_version: number | null, };
