// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { ProjectId } from "./ProjectId.js";
import type { ProviderBinding } from "./ProviderBinding.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type AgentNativeToolTarget = { "type": "provider", binding: ProviderBinding, } | { "type": "host", project: ProjectId, capability: CapabilityKey,
/**
 * Captured by the caller before Send, for example its selected branch.
 * Model arguments cannot include or replace these top-level fields.
 */
fixed_arguments: { [key in string]: JsonValue }, };
