// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

export type AgentContextSelection = { source: string, label: string,
/**
 * Owner-specific reference/observation, validated by the registered source.
 */
reference: JsonValue, inclusion: string, };
