// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type AgentContextPreview = { selection: AgentContextSelection, title: string, description: string, text: string, native_data: JsonValue, columns: Array<string>, rows: Array<Array<string>>, image_base64: string | null, image_mime_type: string | null, inclusions: Array<string>, truncated: boolean, };
