// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { AgentDecision } from "./AgentDecision.js";
import type { AgentMessage } from "./AgentMessage.js";
import type { AgentProvider } from "./AgentProvider.js";

export type AgentClientSession = { id: string, provider: AgentProvider, native_session_id: string, project_root: string, window: AgentControllerRef, model: string, effort: string | null, state: string, messages: Array<AgentMessage>, activity: Array<string>, decisions: Array<AgentDecision>, error: string | null, truncated: boolean, elapsed_ms: number | null, last_request_id: string | null, };
