// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { AgentTaskCommand } from "./AgentTaskCommand.js";

/**
 * Captured request after the caller's scope and controller liveness were checked.
 * The identity fields are correlation data, not an authorization credential.
 */
export type AgentTaskRequest = { project_root: string, window: AgentControllerRef, request_id: string, command: AgentTaskCommand, };
