// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderBinding } from "./ProviderBinding.js";

export type AgentNativeToolSelection = { name: string, binding: ProviderBinding, };
