// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentUsageObservation } from "./AgentUsageObservation.js";

export type AgentTaskEvent = { usage?: AgentUsageObservation, sequence: number, event_id: string, request_id: string | null, generation: number, native_session_id: string, native_turn_id: string | null, native_item_id: string | null, kind: string, role: string | null, text: string, status: string | null,
/**
 * native_history or observation; never re-sent as model memory.
 */
source: string, observed_at_ms: number, };
