// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ProjectAgentTaskRef } from "./ProjectAgentTaskRef.js";

export type AgentHandoffCommand = { project_root: string, window: AgentControllerRef, request_id: string, source: ProjectAgentTaskRef, source_revision: string, target: ProjectAgentTaskRef, target_draft_version: number, target_control_generation: number | null, body: string, context: Array<AgentContextSelection>, };
