// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCommandReceipt } from "./AgentCommandReceipt.js";
import type { AgentTaskDetail } from "./AgentTaskDetail.js";

export type AgentTaskCommandResult = { receipt: AgentCommandReceipt, detail: AgentTaskDetail, };
