// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { AgentDraftContent } from "./AgentDraftContent.js";
import type { ProjectAgentTaskRef } from "./ProjectAgentTaskRef.js";

export type AgentHandoffTargetSnapshot = { target: ProjectAgentTaskRef, title: string, draft: AgentDraftContent, draft_version: number, controller: AgentControllerRef, control_generation: number | null, writable: boolean, reason: string | null, };
