// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ApplicationCaptureSummary } from "./ApplicationCaptureSummary.js";
import type { ApplicationCommandState } from "./ApplicationCommandState.js";
import type { ApplicationDocumentRef } from "./ApplicationDocumentRef.js";
import type { ApplicationDocumentSummary } from "./ApplicationDocumentSummary.js";
import type { ApplicationStepReceipt } from "./ApplicationStepReceipt.js";
import type { CallerIdentity } from "./CallerIdentity.js";

export type ApplicationCommandReceipt = { window: AgentControllerRef, request_id: string, actor: CallerIdentity, state: ApplicationCommandState, created_at_ms: number, claim_expires_at_ms: number, claimed_at_ms: number | null, completed_at_ms: number | null, context_version: string | null, capture: ApplicationCaptureSummary | null, save: ApplicationStepReceipt | null, run: ApplicationStepReceipt | null, diagnostic: string | null,
/**
 * Versions acknowledged by this exact local command, independent of later edits.
 */
applied_documents?: Array<ApplicationDocumentRef>,
/**
 * Exact acknowledged snapshots. Use sha256 to read this document version;
 * neither document_version nor the saved base_hash is the draft checksum.
 */
applied_document_summaries?: Array<ApplicationDocumentSummary>,
/**
 * The resident editor acknowledged the successful save; a changed draft is not adopted.
 */
save_synchronized?: boolean, };
