// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationExecutionTarget = { workspace_instance_id: string, native_session_id: string, };
