// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApplicationTextEdit = {
/**
 * Zero-based UTF-16 offsets in normalized editor content, excluding BOM.
 */
from: number, to: number, insert: string, };
