// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ApplicationAction } from "./ApplicationAction.js";
import type { ApplicationExecutionTarget } from "./ApplicationExecutionTarget.js";

export type ApplicationCommandRequest = { window: AgentControllerRef, request_id: string, action: ApplicationAction, execution_target?: ApplicationExecutionTarget, };
