// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationDocumentRef } from "./ApplicationDocumentRef.js";
import type { ApplicationTextEdit } from "./ApplicationTextEdit.js";

export type ApplicationAction = { "kind": "open_document", path: string, expected_context_version: string, } | { "kind": "create_document", path: string | null, text: string, expected_context_version: string, } | { "kind": "edit_document", document: ApplicationDocumentRef, edits: Array<ApplicationTextEdit>, } | { "kind": "save", document: ApplicationDocumentRef, target_path: string | null, } | { "kind": "run_selection", document: ApplicationDocumentRef, } | { "kind": "run_file", document: ApplicationDocumentRef, target_path: string | null, } | { "kind": "unsupported" };
