// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAgentEvent } from "./ComponentAgentEvent.js";

export type ComponentAgentEventPage = { events: Array<ComponentAgentEvent>, cursor: number, history_gap: boolean, };
