// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationDocumentRef } from "./ApplicationDocumentRef.js";
import type { ComponentAgentBudget } from "./ComponentAgentBudget.js";
import type { ComponentAgentContext } from "./ComponentAgentContext.js";
import type { ComponentAgentPermission } from "./ComponentAgentPermission.js";
import type { ComponentAgentProfile } from "./ComponentAgentProfile.js";
import type { ComponentAgentRecovery } from "./ComponentAgentRecovery.js";
import type { ComponentAgentRunState } from "./ComponentAgentRunState.js";
import type { ComponentAgentStart } from "./ComponentAgentStart.js";
import type { ComponentAgentTaskIntent } from "./ComponentAgentTaskIntent.js";
import type { ComponentDocumentGrant } from "./ComponentDocumentGrant.js";
import type { ComponentModelConnection } from "./ComponentModelConnection.js";

export type ComponentAgentRun = { document_grants: Array<ComponentDocumentGrant>, task_intent?: ComponentAgentTaskIntent, permissions: Array<ComponentAgentPermission>, run_id: string, request: ComponentAgentStart, profile: ComponentAgentProfile, state: ComponentAgentRunState,
/**
 * Fixed configuration for this run. Contains references, never credentials.
 */
model: ComponentModelConnection, budget: ComponentAgentBudget, model_calls: number, tool_calls: number, tool_result_bytes: number, input_tokens: number | null, output_tokens: number | null, event_cursor: number, created_at_ms: number, updated_at_ms: number, reason: string | null, context: ComponentAgentContext | null, document_versions: { [key in string]: ApplicationDocumentRef } | null, recovery?: ComponentAgentRecovery, };
