// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentModelConnection } from "./ComponentModelConnection.js";

export type ComponentModelSettings = { version: number, enabled: boolean, connection: ComponentModelConnection | null, };
