// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { AgentDraftContent } from "./AgentDraftContent.js";
import type { ComponentAgentGrant } from "./ComponentAgentGrant.js";
import type { ComponentAgentProfile } from "./ComponentAgentProfile.js";

export type ComponentAgentConversation = { conversation_id: string, title: string, archived: boolean, version: number,
/**
 * User draft CAS is independent of streaming run/event updates.
 */
draft_version: number, controller: AgentControllerRef, profile: ComponentAgentProfile, draft: string, draft_content: AgentDraftContent, draft_grant?: ComponentAgentGrant, active_run_id: string | null, created_at_ms: number, updated_at_ms: number, };
