// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ComponentAgentCommand } from "./ComponentAgentCommand.js";

export type ComponentAgentsCommand = { project_root: string, window: AgentControllerRef, command: ComponentAgentCommand, };
