// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAgentEvidence } from "./ComponentAgentEvidence.js";
import type { ComponentToolPhase } from "./ComponentToolPhase.js";
import type { OperationId } from "./OperationId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ComponentToolReceipt = { receipt_id: string, run_id: string, model_call: number, tool_call_id: string, capability: string, arguments_digest: string, action_digest: string, client_request_id: string, mutation: boolean, phase: ComponentToolPhase, operation_id: OperationId | null, application_request_id: string | null, result: JsonValue | null, evidence: Array<ComponentAgentEvidence>, updated_at_ms: number, };
