// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAgentQuery } from "./ComponentAgentQuery.js";

export type ComponentAgentsQuery = { project_root: string, query: ComponentAgentQuery, };
