// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentPermissionPolicy } from "./ComponentPermissionPolicy.js";
import type { ComponentPermissionState } from "./ComponentPermissionState.js";
import type { ComponentTaskAuthorization } from "./ComponentTaskAuthorization.js";

export type ComponentAgentPermission = { decision_id: string, receipt_id: string, action_digest: string, tool: string, title: string, details: string, authorization: ComponentTaskAuthorization, policy: ComponentPermissionPolicy, state: ComponentPermissionState, };
