// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAsset } from "./AgentAsset.js";
import type { ApplicationDocumentRef } from "./ApplicationDocumentRef.js";
import type { MediaReference } from "./MediaReference.js";
import type { OperationId } from "./OperationId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ComponentAgentEvidence = { "kind": "attachment", conversation_id: string, asset: AgentAsset, } | { "kind": "operation", operation_id: OperationId, } | { "kind": "media", reference: MediaReference, } | { "kind": "document", document: ApplicationDocumentRef, } | { "kind": "file", path: string, sha256: string, } | { "kind": "observation", capability: string, reference: JsonValue, };
