// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ComponentAgentSession } from "./ComponentAgentSession.js";

export type ComponentSourcePreviewRequest = { project_root: string, window: AgentControllerRef, session: ComponentAgentSession | null, selection: AgentContextSelection, };
