// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationDocumentRef } from "./ApplicationDocumentRef.js";

export type ComponentDocumentGrant = { document: ApplicationDocumentRef, allow_save: boolean,
/**
 * Exact project-relative destination; Save As cannot expand this scope.
 */
path: string | null, };
