// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { ComponentAgentEvidence } from "./ComponentAgentEvidence.js";
import type { ComponentSourceObservation } from "./ComponentSourceObservation.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ComponentSourceSnapshot = { selection: AgentContextSelection, title: string, description: string, text: string, native_data: JsonValue, truncated: boolean, observations: Array<ComponentSourceObservation>, evidence: Array<ComponentAgentEvidence>, };
