// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservationCompleteness } from "./ObservationCompleteness.js";
import type { QueryStatus } from "./QueryStatus.js";
import type { TargetRef } from "./TargetRef.js";

export type ComponentSourceObservation = { capability: string, target: TargetRef, source: string, observed_at_ms: number, status: QueryStatus, completeness: ObservationCompleteness, notices: Array<string>, };
