// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Approval policy is independent of the work selected by the Agent.
 */
export type ComponentPermissionPolicy = "ask" | "auto_approval" | "full_access";
