// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ComponentAgentSession } from "./ComponentAgentSession.js";

export type ComponentSourceSearch = { project_root: string, window: AgentControllerRef, session: ComponentAgentSession | null, source: string, text: string, limit: number, };
