// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentRequestedAction } from "./ComponentRequestedAction.js";

export type ComponentIntentAction = { action: ComponentRequestedAction,
/**
 * None denotes execution in the run's already bound R session.
 */
document_id: string | null,
/**
 * An exact project-relative destination, including a not-yet-created file.
 */
path: string | null, };
