// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDraftContent } from "./AgentDraftContent.js";
import type { ComponentAgentGrant } from "./ComponentAgentGrant.js";

export type ComponentAgentDraftUpdate = { conversation_id: string, draft_version: number, text: string, content?: AgentDraftContent, grant?: ComponentAgentGrant, };
