// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentSubmissionState } from "./ComponentSubmissionState.js";
import type { Diagnostic } from "./Diagnostic.js";

export type ComponentRequestFailure = { error: string, diagnostic: Diagnostic, submission: ComponentSubmissionState, request_id: string | null,
/**
 * Present only when the active diagnostic belongs to the same visible scope.
 */
existing_request_id: string | null, };
