// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplicationCommandState } from "./ApplicationCommandState.js";
import type { ApplicationDocumentRef } from "./ApplicationDocumentRef.js";
import type { ComponentRecoveredOperation } from "./ComponentRecoveredOperation.js";
import type { ComponentRecoveryState } from "./ComponentRecoveryState.js";

export type ComponentRecoveredTool = { receipt_id: string, state: ComponentRecoveryState, application_request_id: string | null, application_state: ApplicationCommandState | null, operations: Array<ComponentRecoveredOperation>, documents: Array<ApplicationDocumentRef>, note: string | null, };
