// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ComponentModelTestKind } from "./ComponentModelTestKind.js";

export type ComponentModelTestRequest = { project_root: string, window: AgentControllerRef, request_id: string, model_settings_version: number, kind: ComponentModelTestKind, };
