// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComponentAgentBudget = { model_calls: number, tool_calls: number, context_bytes: number, tool_result_bytes: number, output_tokens: number, duration_ms: number, };
