// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentAgentMode } from "./ComponentAgentMode.js";
import type { ComponentAgentSession } from "./ComponentAgentSession.js";
import type { ComponentDocumentGrant } from "./ComponentDocumentGrant.js";
import type { ComponentFileGrant } from "./ComponentFileGrant.js";
import type { ComponentPermissionPolicy } from "./ComponentPermissionPolicy.js";

export type ComponentAgentGrant = {
/**
 * Absent only in already recorded requests using the former work modes.
 */
permission_policy?: ComponentPermissionPolicy, mode: ComponentAgentMode, session: ComponentAgentSession | null, documents: Array<ComponentDocumentGrant>, files: Array<ComponentFileGrant>, };
