// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ComponentModelConnection } from "./ComponentModelConnection.js";
import type { ComponentModelTestKind } from "./ComponentModelTestKind.js";
import type { ComponentModelTestState } from "./ComponentModelTestState.js";

export type ComponentModelDiagnostic = { request_id: string, version: number, window: AgentControllerRef, model_settings_version: number, connection_digest: string, model: ComponentModelConnection, kind: ComponentModelTestKind, state: ComponentModelTestState, created_at_ms: number, updated_at_ms: number, detail: string | null, };
