// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentIntentAction } from "./ComponentIntentAction.js";

export type ComponentAgentTaskIntent = { request_id: string, request_excerpt: string, actions: Array<ComponentIntentAction>, };
