// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextSelection } from "./AgentContextSelection.js";
import type { AgentControllerRef } from "./AgentControllerRef.js";
import type { ComponentAgentGrant } from "./ComponentAgentGrant.js";
import type { ComponentContinuation } from "./ComponentContinuation.js";

export type ComponentAgentStart = {
/**
 * Immutable user-uploaded attachment references; bytes stay in Application asset storage.
 */
assets?: Array<string>, continuation?: ComponentContinuation, request_id: string, conversation_id: string, conversation_version: number, window: AgentControllerRef, model_settings_version: number, text: string, grant: ComponentAgentGrant, sources: Array<AgentContextSelection>, };
