// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentCredentialRef } from "./ComponentCredentialRef.js";
import type { ComponentModelProtocol } from "./ComponentModelProtocol.js";

export type ComponentModelConnection = { protocol: ComponentModelProtocol, base_url: string, model: string, credential: ComponentCredentialRef, };
