// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentModel } from "./AgentModel.js";
import type { AgentNativeCapabilities } from "./AgentNativeCapabilities.js";
import type { AgentProvider } from "./AgentProvider.js";

export type LocalAgent = { provider: AgentProvider, executable: string | null, version: string | null, models: Array<AgentModel>, selected_model: string | null, selected_effort: string | null, discovery_ms: number, error: string | null, setup_required: boolean, capabilities: AgentNativeCapabilities, };
