// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAgentTaskSummary } from "./ProjectAgentTaskSummary.js";

export type ProjectAgentTaskPage = { attention_count: number, tasks: Array<ProjectAgentTaskSummary>, attention: Array<ProjectAgentTaskSummary>, next: string | null, running: number, permissions: number, };
