// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRef } from "./CapabilityRef.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type QueryRequest = { capability: CapabilityRef, arguments: JsonValue, };
