// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadAgentAsset = { project_root: string, task_id: string, asset_id: string, };
