// Runs from this R package, including a standalone source assembly.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),check=process.argv.includes('--check');
assert.ok(process.argv.slice(2).every(arg=>arg==='--check'),'Use no arguments to generate, or --check');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'rho-r-protocol-'));
const files=(directory,prefix='')=>fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{
  const relative=path.join(prefix,entry.name);
  return entry.isDirectory()?files(path.join(directory,entry.name),relative):[relative];
}).sort();
function synchronize(file,text){
  if(check)assert.equal(fs.readFileSync(file,'utf8'),text,`Stale R protocol: ${file}`);
  else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
}
try{
  execFileSync(process.env.RHO_PLUGIN_CARGO??'cargo',['run','--manifest-path',path.join(root,'api/Cargo.toml'),'-p','rho-r-api','--bin','export-r-plugin','--locked','--offline','--',temporary],{cwd:root,stdio:'inherit'});
  const sdk=path.join(root,'sdk');
  for(const section of ['types','schema']){
    const names=files(path.join(temporary,section));
    const targetNames=names.map(name=>section==='types'?name.replace(/\.ts$/,'.d.ts'):name);
    if(check)assert.deepEqual(files(path.join(sdk,section)),targetNames);
    for(const name of names){
      let text=fs.readFileSync(path.join(temporary,section,name),'utf8').replace(/[ \t]+$/gm,'');
      if(section==='types')text=text.replace(/(from\s+["'])(\.[^"']+)(["'])/g,(_m,start,spec,end)=>`${start}${spec}.js${end}`);
      synchronize(path.join(sdk,section,section==='types'?name.replace(/\.ts$/,'.d.ts'):name),text);
    }
    if(!check)for(const name of files(path.join(sdk,section)))if(!targetNames.includes(name)){
      assert.ok(section==='schema'||fs.readFileSync(path.join(sdk,section,name),'utf8').startsWith('// This file was generated by [ts-rs]'));
      fs.unlinkSync(path.join(sdk,section,name));
    }
  }
  synchronize(path.join(sdk,'index.d.ts'),files(path.join(temporary,'types')).map(name=>`export type * from "./types/${name.replace(/\.ts$/,'.js')}";`).join('\n')+'\n');
  const manifest=JSON.parse(fs.readFileSync(path.join(root,'plugin.json'),'utf8'));
  const schema=name=>JSON.parse(fs.readFileSync(path.join(temporary,'schema',name+'.json'),'utf8'));
  const source={view_id:'console-view',label:'Console',kind:'console'};
  const session='copy-session-from-r.session';
  const additions=[
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.execute'&&item.capability.version===1)),
      capability:{id:'r.format',version:1},title:'Format R code',description:'Format captured text in the exact existing session using an installed styler. Does not evaluate the text, install tooling or write a project file. The original retained report contains the complete FormatResult; value_in_report marks an oversized inline value.',
      input_schema:schema('format'),output_schema:schema('execute-result'),examples:[{expected_session:session,code:'value=1',source:{view_id:'editor-view',label:'analysis.R',kind:'format'}}]},
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.execute'&&item.capability.version===1)),
      capability:{id:'r.execute',version:2},title:'Execute R input with source',description:'Execute the supplied code, output mode and source labels in the exact admitted session. Labels do not attest to a Host document capture.',
      input_schema:schema('execute'),output_schema:schema('execute-result'),examples:[{expected_session:'copy-session-from-r.session',run:{code:'1 + 1',output_mode:'console',source}}]},
    ...[
      ['r.inspection_state','Observe R inspection readiness','Observe this exact owner without starting R. Session-scoped cache keys change around native execution, including runs missed between polls, and never establish scientific results or preconditions.','inspection-state-arguments','inspection-state',{expected_session:null}],
      ['r.check_code','Check R code','Check completeness in the existing idle session without evaluating code.','check-code','code-completeness',{expected_session:'copy-session-from-r.session',code:'1 + 1'}],
      ['r.output_events','Observe original R output','Read bounded events while a run is active. Observations never establish terminal execution status.','read-events','events-observation',{expected_session:'copy-session-from-r.session',operation_id:'original-operation',after_sequence:0,limit:100}],
      ['r.list_objects','List R objects','Read a bounded stable binding directory in the exact expected_session. Reading never starts R or evaluates active/lazy bindings.','list-objects','object-directory',{expected_session:session,limit:100}],
      ['r.observe_object','Observe an R object','Create a scoped read-only observation for progressive inspection in the exact expected_session.','observe-object','object-observation',{expected_session:session,name:'iris'}],
      ['r.read_object','Read an R object observation','Read bounded structure, values, children, table slices or text using the original object reference and exact expected_session.','read-object','object-read',{expected_session:session,object_ref:'copy_object_ref_from_r_observe_object',kind:'structure'}],
      ['r.inspect_object','Preview an R binding','Read a bounded binding preview in the exact expected_session without forcing active/lazy bindings.','inspect-object','object-preview',{expected_session:session,name:'iris',max_items:20}],
      ['r.packages','Observe installed R packages','Read package metadata in the exact expected_session. Grouped counts and copy details continue one observation; no package is installed, loaded, attached or tested.','packages','package-observation',{expected_session:session,grouped:true,limit:100}],
      ['r.package_index','Inspect an observed package copy','Read the static index of the original observed package copy in the exact expected_session.','package-index','package-index-observation',{expected_session:session,observation_id:'copy_observation_id_from_r_packages',package:'base',library_path:'copy-library-path-from-r.packages',limit:100}],
      ['r.read_help','Read observed R help','Read bounded help text or HTML from the exact installed copy and file identities returned by r.package_index, in the exact expected_session.','read-help','help-observation',{expected_session:session,observation_id:'copy_observation_id_from_r_packages',package:'base',library_path:'copy-library-path-from-r.packages',topic:'sum',expected_index_files:[1,2,3,4].map(index=>({path:`copy_index_file_path_${index}`,digest:'copy-original-index-file-digest'})),limit_bytes:16384}],
    ].map(([id,title,description,input,output,example])=>({capability:{id,version:1},kind:'query',title,description,input_schema:schema(input),examples:[example],output_schema:schema(output),recovery_schema:true,required_scopes:['workspace.read'],effects:[],cancellation:'unsupported',preflight:null})),
  ];
  for(const addition of additions){const index=manifest.capabilities.findIndex(item=>item.capability.id===addition.capability.id&&item.capability.version===addition.capability.version);if(index<0)manifest.capabilities.push(addition);else manifest.capabilities[index]=addition;}
  synchronize(path.join(root,'plugin.json'),JSON.stringify(manifest,null,2)+'\n');
  console.log(`R public declarations, schemas and contributed contracts ${check?'verified':'generated'}.`);
}finally{fs.rmSync(temporary,{recursive:true,force:true});}
