// Runs from this R package, including a standalone source assembly.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),check=process.argv.includes('--check');
assert.ok(process.argv.slice(2).every(arg=>arg==='--check'),'Use no arguments to generate, or --check');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'rho-r-protocol-'));
const files=(directory,prefix='')=>fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{
  const relative=path.join(prefix,entry.name);
  return entry.isDirectory()?files(path.join(directory,entry.name),relative):[relative];
}).sort();
function synchronize(file,text){
  if(check)assert.equal(fs.readFileSync(file,'utf8'),text,`Stale R protocol: ${file}`);
  else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
}
try{
  execFileSync(process.env.RHO_PLUGIN_CARGO??'cargo',['run','--manifest-path',path.join(root,'api/Cargo.toml'),'-p','rho-r-api','--bin','export-r-plugin','--locked','--offline','--',temporary],{cwd:root,stdio:'inherit'});
  const sdk=path.join(root,'sdk');
  for(const section of ['types','schema']){
    const names=files(path.join(temporary,section));
    const targetNames=names.map(name=>section==='types'?name.replace(/\.ts$/,'.d.ts'):name);
    if(check)assert.deepEqual(files(path.join(sdk,section)),targetNames);
    for(const name of names){
      let text=fs.readFileSync(path.join(temporary,section,name),'utf8').replace(/[ \t]+$/gm,'');
      if(section==='types')text=text.replace(/(from\s+["'])(\.[^"']+)(["'])/g,(_m,start,spec,end)=>`${start}${spec}.js${end}`);
      synchronize(path.join(sdk,section,section==='types'?name.replace(/\.ts$/,'.d.ts'):name),text);
    }
    if(!check)for(const name of files(path.join(sdk,section)))if(!targetNames.includes(name)){
      assert.ok(section==='schema'||fs.readFileSync(path.join(sdk,section,name),'utf8').startsWith('// This file was generated by [ts-rs]'));
      fs.unlinkSync(path.join(sdk,section,name));
    }
  }
  synchronize(path.join(sdk,'index.d.ts'),files(path.join(temporary,'types')).map(name=>`export type * from "./types/${name.replace(/\.ts$/,'.js')}";`).join('\n')+'\n');
  const manifest=JSON.parse(fs.readFileSync(path.join(root,'plugin.json'),'utf8'));
  const schema=name=>JSON.parse(fs.readFileSync(path.join(temporary,'schema',name+'.json'),'utf8'));
  const source={view_id:'console-view',label:'Console',kind:'console'};
  const additions=[
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.execute'&&item.capability.version===1)),
      capability:{id:'r.execute',version:2},title:'Execute R input with source',description:'Execute the supplied code, output mode and source labels in the exact admitted session. Labels do not attest to a Host document capture.',
      input_schema:schema('execute'),output_schema:schema('execute-result'),examples:[{expected_session:'copy-session-from-r.session',run:{code:'1 + 1',output_mode:'console',source}}]},
    ...[
      ['r.check_code','Check R code','Check completeness in the existing idle session without evaluating code.','check-code','code-completeness',{expected_session:'copy-session-from-r.session',code:'1 + 1'}],
      ['r.output_events','Observe original R output','Read bounded events while a run is active. Observations never establish terminal execution status.','read-events','events-observation',{expected_session:'copy-session-from-r.session',operation_id:'original-operation',after_sequence:0,limit:100}],
    ].map(([id,title,description,input,output,example])=>({capability:{id,version:1},kind:'query',title,description,input_schema:schema(input),examples:[example],output_schema:schema(output),recovery_schema:true,required_scopes:['workspace.read'],effects:[],cancellation:'unsupported',preflight:null})),
  ];
  for(const addition of additions){const index=manifest.capabilities.findIndex(item=>item.capability.id===addition.capability.id&&item.capability.version===addition.capability.version);if(index<0)manifest.capabilities.push(addition);else manifest.capabilities[index]=addition;}
  synchronize(path.join(root,'plugin.json'),JSON.stringify(manifest,null,2)+'\n');
  console.log(`R public declarations, schemas and contributed contracts ${check?'verified':'generated'}.`);
}finally{fs.rmSync(temporary,{recursive:true,force:true});}
