// Runs from this R package, including a standalone source assembly.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),check=process.argv.includes('--check');
assert.ok(process.argv.slice(2).every(arg=>arg==='--check'),'Use no arguments to generate, or --check');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'rho-r-protocol-'));
const files=(directory,prefix='')=>fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{
  const relative=path.join(prefix,entry.name);
  return entry.isDirectory()?files(path.join(directory,entry.name),relative):[relative];
}).sort();
function synchronize(file,text){
  if(check)assert.equal(fs.readFileSync(file,'utf8'),text,`Stale R protocol: ${file}`);
  else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
}
try{
  execFileSync(process.env.RHO_PLUGIN_CARGO??'cargo',['run','--manifest-path',path.join(root,'api/Cargo.toml'),'-p','rho-r-api','--bin','export-r-plugin','--locked','--offline','--',temporary],{cwd:root,stdio:'inherit'});
  const sdk=path.join(root,'sdk');
  for(const section of ['types','schema']){
    const names=files(path.join(temporary,section));
    const targetNames=names.map(name=>section==='types'?name.replace(/\.ts$/,'.d.ts'):name);
    if(check)assert.deepEqual(files(path.join(sdk,section)),targetNames);
    for(const name of names){
      let text=fs.readFileSync(path.join(temporary,section,name),'utf8').replace(/[ \t]+$/gm,'');
      if(section==='types')text=text.replace(/(from\s+["'])(\.[^"']+)(["'])/g,(_m,start,spec,end)=>`${start}${spec}.js${end}`);
      synchronize(path.join(sdk,section,section==='types'?name.replace(/\.ts$/,'.d.ts'):name),text);
    }
    if(!check)for(const name of files(path.join(sdk,section)))if(!targetNames.includes(name)){
      assert.ok(section==='schema'||fs.readFileSync(path.join(sdk,section,name),'utf8').startsWith('// This file was generated by [ts-rs]'));
      fs.unlinkSync(path.join(sdk,section,name));
    }
  }
  synchronize(path.join(sdk,'index.d.ts'),files(path.join(temporary,'types')).map(name=>`export type * from "./types/${name.replace(/\.ts$/,'.js')}";`).join('\n')+'\n');
  const manifest=JSON.parse(fs.readFileSync(path.join(root,'plugin.json'),'utf8'));
  const schema=name=>JSON.parse(fs.readFileSync(path.join(temporary,'schema',name+'.json'),'utf8'));
  const source={view_id:'console-view',label:'Console',kind:'console'};
  const session='copy-session-from-r.session';
  const environmentScopes=['workspace.run_r','project.read','environment.read','environment.write','operation.read','resources.read'];
  const environmentExample={environment:{binding:{capability:{id:'environment.library',version:2},provider:{plugin:'org.rho.environment',instance:'copy-original-instance',revision:'sha256:'+'a'.repeat(64),artifact:'sha256:'+'b'.repeat(64)},project:'copy-original-project',target:null},realization:'copy-original-realization'}};
  const recoveryRead=['workspace.read','operation.read','resources.read','project.references.read'];
  const reference={project:'copy-original-project',provider:{plugin:'org.rho.r',instance:'copy-original-instance',revision:'sha256:'+'a'.repeat(64),artifact:'sha256:'+'b'.repeat(64)},operation_id:'copy-original-capture-operation',digest:'sha256:'+'c'.repeat(64),bytes:1024};
  const additions=[
    {capability:{id:'r.prepare_checkpoint',version:1},kind:'query',title:'Prepare R recovery',description:'Qualify the exact native target and original core capture through explicitly selected read grants. Never starts R, builds a helper, loads a namespace or recovers implicitly.',input_schema:{type:'object'},output_schema:{type:'object'},examples:[{capability:{id:'r.capture_checkpoint',version:1},arguments:{expected_session:session},target:null,preconditions:null}],recovery_schema:true,required_scopes:['workspace.run_r'],effects:[],cancellation:'unsupported',preflight:null},
    ...[
      ['r.capture_checkpoint','Capture R recovery','Capture the eligible native object graph from the exact session into bounded scoped storage. Retain a complete metadata resource; skipped bindings and partial coverage remain explicit. Automatic captures require an idle settled queue.','capture-checkpoint','checkpoint-capture-output',{expected_session:session},['workspace.run_r'],['recovery.capture'],'request'],
      ['r.restore_checkpoint','Restore R recovery','Restore one exact committed copy into the existing empty candidate. Verify the full payload digest, native installation, libraries and inventory; retain namespace effects and the original restore report. Never starts a replacement R session.','restore-checkpoint','checkpoint-restore-output',{expected_session:session,reference},['workspace.run_r',...recoveryRead],['r.workspace','r.namespaces'],'request'],
      ['r.reconcile_checkpoint','Reconcile an original capture','Qualify a failed, cancelled or uncertain original operation and adopt its complete native capture into a new operation. Does not replay R code or rewrite the original outcome.','reconcile-checkpoint','checkpoint-capture-output',{source_operation_id:reference.operation_id},['workspace.run_r','workspace.read','operation.read','resources.read'],['recovery.adopt'],'unsupported'],
      ['r.pin_checkpoint','Pin R recovery','Record an exact copy pin using the latest original control operation as its precondition. Native intent alone never establishes a committed pin.','pin-checkpoint','checkpoint-control-output',{reference,expected_control:null,pinned:true},['workspace.run_r',...recoveryRead],['recovery.pin'],'unsupported'],
      ['r.delete_checkpoint','Delete R recovery','Logically retire an unpinned copy through the core journal, then attempt native payload cleanup after confirmed settlement. Observe the copy to distinguish logical deletion from remaining bytes.','delete-checkpoint','checkpoint-control-output',{reference,expected_control:null},['workspace.run_r',...recoveryRead],['recovery.delete'],'unsupported'],
      ['r.purge_checkpoint','Clean up deleted recovery','Retry native payload removal for the exact committed deletion. Keep original metadata and operation history; report payload_removed only after confirmed absence.','purge-checkpoint','checkpoint-purge-output',{reference,deletion_operation_id:'copy-original-delete-operation'},['workspace.run_r',...recoveryRead],['recovery.cleanup'],'unsupported'],
    ].map(([id,title,description,input,output,example,required_scopes,effects,cancellation])=>({capability:{id,version:1},kind:'operation',title,description,input_schema:schema(input),output_schema:schema(output),examples:[example],recovery_schema:true,required_scopes,effects,cancellation,preflight:{id:'r.prepare_checkpoint',version:1}})),
    ...[
      ['r.checkpoint','Observe an original recovery copy','Read committed control history and native payload presence without starting R. Presence is a length/identity observation, not a fresh full digest check.','checkpoint-arguments','checkpoint-observation',{reference},recoveryRead],
      ['r.read_checkpoint','Read original recovery bytes','Read at most 64 KiB from the exact committed nondeleted native copy. Qualify original operation, caller visibility and control history; the reference is an identity, not permission.','read-checkpoint','checkpoint-chunk',{reference,offset:0,limit:65536},recoveryRead],
      ['r.checkpoints','List original recovery results','Read one bounded visible journal page of successful capture/reconciliation results. Empty pages can have a continuation; inspect each reference for current native and control state.','list-checkpoints','checkpoint-page',{before_cursor:null,limit:20},['workspace.read','operation.read']],
    ].map(([id,title,description,input,output,example,required_scopes])=>({capability:{id,version:1},kind:'query',title,description,input_schema:schema(input),output_schema:schema(output),examples:[example],recovery_schema:true,required_scopes,effects:[],cancellation:'unsupported',preflight:null})),
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.create_session'&&item.capability.version===1)),
      capability:{id:'r.create_session',version:2},title:'Create R with a realized Environment',description:'Create one session using an exact original Environment realization. Explicitly delegates native verification to the selected provider, preserves its original operation and report, then checks the new native R installation. Does not rebind an existing session or replay an unconfirmed creation.',
      input_schema:schema('create-session'),output_schema:schema('session-created'),examples:[environmentExample],required_scopes:environmentScopes,effects:['r.session','environment.verify','process.spawn','network'],preflight:{id:'r.prepare_environment',version:2}},
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.prepare'&&item.capability.version===1)),
      capability:{id:'r.prepare_environment',version:2},title:'Select Environment for a new R session',description:'Read and pin a verified original library through the exact selected Environment provider. Never starts R or tests namespace loading.',
      examples:[{capability:{id:'r.create_session',version:2},arguments:environmentExample,target:null,preconditions:null}],required_scopes:environmentScopes},
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.execute'&&item.capability.version===1)),
      capability:{id:'r.format',version:1},title:'Format R code',description:'Format captured text in the exact existing session using an installed styler. Does not evaluate the text, install tooling or write a project file. The original retained report contains the complete FormatResult; value_in_report marks an oversized inline value.',
      input_schema:schema('format'),output_schema:schema('execute-result'),examples:[{expected_session:session,code:'value=1',source:{view_id:'editor-view',label:'analysis.R',kind:'format'}}]},
    {...structuredClone(manifest.capabilities.find(item=>item.capability.id==='r.execute'&&item.capability.version===1)),
      capability:{id:'r.execute',version:2},title:'Execute R input with source',description:'Execute the supplied code, output mode and source labels in the exact admitted session. Labels do not attest to a Host document capture.',
      input_schema:schema('execute'),output_schema:schema('execute-result'),examples:[{expected_session:'copy-session-from-r.session',run:{code:'1 + 1',output_mode:'console',source}}]},
    ...[
      ['r.inspection_state','Observe R inspection readiness','Observe this exact owner without starting R. Session-scoped cache keys change around native execution, including runs missed between polls, and never establish scientific results or preconditions.','inspection-state-arguments','inspection-state',{expected_session:null}],
      ['r.check_code','Check R code','Check completeness in the existing idle session without evaluating code.','check-code','code-completeness',{expected_session:'copy-session-from-r.session',code:'1 + 1'}],
      ['r.output_events','Observe original R output','Read bounded events while a run is active. Observations never establish terminal execution status.','read-events','events-observation',{expected_session:'copy-session-from-r.session',operation_id:'original-operation',after_sequence:0,limit:100}],
      ['r.list_objects','List R objects','Read a bounded stable binding directory in the exact expected_session. Reading never starts R or evaluates active/lazy bindings.','list-objects','object-directory',{expected_session:session,limit:100}],
      ['r.observe_object','Observe an R object','Create a scoped read-only observation for progressive inspection in the exact expected_session.','observe-object','object-observation',{expected_session:session,name:'iris'}],
      ['r.read_object','Read an R object observation','Read bounded structure, values, children, table slices or text using the original object reference and exact expected_session.','read-object','object-read',{expected_session:session,object_ref:'copy_object_ref_from_r_observe_object',kind:'structure'}],
      ['r.inspect_object','Preview an R binding','Read a bounded binding preview in the exact expected_session without forcing active/lazy bindings.','inspect-object','object-preview',{expected_session:session,name:'iris',max_items:20}],
      ['r.packages','Observe installed R packages','Read package metadata in the exact expected_session. Grouped counts and copy details continue one observation; no package is installed, loaded, attached or tested.','packages','package-observation',{expected_session:session,grouped:true,limit:100}],
      ['r.package_index','Inspect an observed package copy','Read the static index of the original observed package copy in the exact expected_session.','package-index','package-index-observation',{expected_session:session,observation_id:'copy_observation_id_from_r_packages',package:'base',library_path:'copy-library-path-from-r.packages',limit:100}],
      ['r.read_help','Read observed R help','Read bounded help text or HTML from the exact installed copy and file identities returned by r.package_index, in the exact expected_session.','read-help','help-observation',{expected_session:session,observation_id:'copy_observation_id_from_r_packages',package:'base',library_path:'copy-library-path-from-r.packages',topic:'sum',expected_index_files:[1,2,3,4].map(index=>({path:`copy_index_file_path_${index}`,digest:'copy-original-index-file-digest'})),limit_bytes:16384}],
    ].map(([id,title,description,input,output,example])=>({capability:{id,version:1},kind:'query',title,description,input_schema:schema(input),examples:[example],output_schema:schema(output),recovery_schema:true,required_scopes:['workspace.read'],effects:[],cancellation:'unsupported',preflight:null})),
  ];
  for(const addition of additions){const index=manifest.capabilities.findIndex(item=>item.capability.id===addition.capability.id&&item.capability.version===addition.capability.version);if(index<0)manifest.capabilities.push(addition);else manifest.capabilities[index]=addition;}
  manifest.optional_requires??=[];
  for(const requirement of [
    {capability:{id:'environment.library',version:2},scopes:['project.read','environment.read','operation.read','resources.read']},
    {capability:{id:'environment.verify',version:2},scopes:['project.read','environment.write','operation.read','resources.read']},
    {capability:{id:'resources.read',version:1},scopes:['resources.read']},
    {capability:{id:'operation.get',version:1},scopes:['operation.read']},
    {capability:{id:'operation.list_recent',version:1},scopes:['operation.read']},
    {capability:{id:'operation.project_coverage',version:1},scopes:['operation.read','project.references.read']},
  ]){const index=manifest.optional_requires.findIndex(item=>item.capability.id===requirement.capability.id&&item.capability.version===requirement.capability.version);if(index<0)manifest.optional_requires.push(requirement);else manifest.optional_requires[index]=requirement;}
  manifest.configuration_schema.properties.checkpoint_helper_path={type:['string','null'],minLength:1,description:'Existing canonical path to the verified native recovery helper and its adjacent manifest. Never built or installed by plugin activation.'};
  synchronize(path.join(root,'plugin.json'),JSON.stringify(manifest,null,2)+'\n');
  console.log(`R public declarations, schemas and contributed contracts ${check?'verified':'generated'}.`);
}finally{fs.rmSync(temporary,{recursive:true,force:true});}
