[package]
name = "rho-r-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
rho-contract = { path = "../../contract" }
rho-workspace = { path = "../../workspace" }
rho-r-api = { path = "../../../plugins/r/api" }
rho-r-engine = { path = "../../../plugins/r/backend/engine" }
rho-plugin-protocol = { path = "../../plugin-protocol" }
tokio.workspace = true
