// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentRuntimeRecovery } from "./EnvironmentRuntimeRecovery.js";
import type { EnvironmentStageRecovery } from "./EnvironmentStageRecovery.js";

export type EnvironmentRealizeRecovery = EnvironmentStageRecovery | EnvironmentRuntimeRecovery;
