// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { OperationId } from "./OperationId.js";
import type { ResourceReference } from "./ResourceReference.js";

export type EnvironmentRecovery = { operation: OperationId, storage_root: string, native_recovery: ResourceReference | null, report_digest: ContentDigest | null, automatic_reexecution: boolean, action: string, };
