// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledEnvironmentPackage } from "./InstalledEnvironmentPackage.js";

/**
 * Native configuration is established during explicit Host startup or an
 * Environment operation. Reading it never starts R or tests namespace loading.
 */
export type EnvironmentObservation = { r_version: string, platform: string, r_home: string, library_paths: Array<string>, packages: Array<InstalledEnvironmentPackage>, truncated: boolean, jsonlite_library: string,
/**
 * Cached startup/operation probe, not a current loadability guarantee.
 */
renv_available: boolean,
/**
 * Cached startup/operation probe, not a current loadability guarantee.
 */
pak_available: boolean, configuration_observed_at_ms: number, configuration_source: string, inventory_observed_at_ms: number, active_workspace_library: string | null, notices: Array<string>, };
