// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { OperationId } from "./OperationId.js";
import type { ProviderBinding } from "./ProviderBinding.js";
import type { ResourceReference } from "./ResourceReference.js";

/**
 * Current read-only selection of an original, verified realization. This is not
 * a namespace probe or an authorization to change an existing R session.
 */
export type EnvironmentLibrary = { binding: ProviderBinding, realization: OperationId, source: ProviderBinding, report: ResourceReference, project_root: string, storage_root: string, rscript: string, library_path: string, library_digest: ContentDigest, r_version: string, platform: string, };
