// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentObservation } from "./EnvironmentObservation.js";
import type { EnvironmentSnapshotStatus } from "./EnvironmentSnapshotStatus.js";

export type EnvironmentSnapshot = { status: EnvironmentSnapshotStatus, observation: EnvironmentObservation | null, notices: Array<string>, };
