// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamespaceProbe } from "./NamespaceProbe.js";
import type { PackageVersion } from "./PackageVersion.js";

export type EnvironmentRealization = { project_root: string, plan_operation_id: string, manager: string, lock_digest: string, library_path: string, library_digest: string, renv_lockfile: string, r_version: string, platform: string, packages: Array<PackageVersion>, probes: Array<NamespaceProbe>, verified: boolean, restart_required: boolean, activation: string, };
