// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentReportKind } from "./EnvironmentReportKind.js";
import type { OperationId } from "./OperationId.js";
import type { ResourceReference } from "./ResourceReference.js";

export type EnvironmentResult = { operation: OperationId, kind: EnvironmentReportKind, report: ResourceReference,
/**
 * None for planning/configuration; false never means successful verification.
 */
verified: boolean | null, };
