// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessActivity } from "./ProcessActivity.js";

export type EnvironmentStatus = { project_root: string, storage_root: string, rscript: string | null, target_key: string | null, activities: Array<ProcessActivity>, capacity: number, };
