// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion.js";
import type { SourceDigest } from "./SourceDigest.js";

export type EnvironmentPlan = { project_root: string, manager: string, lock_path: string, lock_digest: string, r_version: string, platform: string, packages: Array<PackageVersion>, local_sources: Array<SourceDigest>, };
