// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceRef } from "./InstanceRef.js";

export type EnvironmentConfiguration = {
/**
 * An explicit installed executable; activation never discovers or installs R.
 */
rscript: string | null,
/**
 * Reopen an existing material directory after its previous owner has exited.
 * None uses this instance's Host-provided data directory.
 */
storage_root: string | null,
/**
 * Exact read-only R provider for retained checkpoints. None prefers the original
 * active provider, then a unique active reader; ambiguity retains material.
 */
checkpoint_reader: InstanceRef | null, timeout_seconds: number, };
