// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessReport } from "./ProcessReport.js";

export type EnvironmentRuntimeRecovery = { process: ProcessReport, process_tree_marker: string, tree_cleanup_confirmed: boolean, action: string, };
