// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvironmentConfiguration = {
/**
 * An explicit installed executable; activation never discovers or installs R.
 */
rscript: string | null,
/**
 * Reopen an existing material directory after its previous owner has exited.
 * None uses this instance's Host-provided data directory.
 */
storage_root: string | null, timeout_seconds: number, };
