// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialAction } from "./MaterialAction.js";

export type MaterialChange = { source_operation_id: string, cleanup_operation_id: string, action: MaterialAction, stage_path: string, trash_path: string, bytes: number, recoverable: boolean, };
