// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NamespaceProbe = { name: string, version: string | null, library: string | null, loadable: boolean, error: string | null, };
