// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { ProcessPhase } from "./ProcessPhase.js";

export type ProcessActivity = { operation: OperationId, phase: ProcessPhase, };
