// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamespaceProbe } from "./NamespaceProbe.js";

export type Verification = { verified: boolean, library_digest_matches: boolean, probes: Array<NamespaceProbe>, errors: Array<string>, };
