[package]
name = "rho-r-environment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
rho-environment = { path = "../../environment" }
rho-operation = { path = "../../operation" }
rho-environment-owner = { path = "../../../plugins/environment/backend/owner" }
tokio.workspace = true
