[package]
name = "rho-project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rho-files-owner = { path = "../../plugins/files/backend/owner" }
rho-files-api = { path = "../../plugins/files/api" }
async-trait.workspace = true
rho-contract = { path = "../contract" }
rho-operation = { path = "../operation" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
