[package]
name = "rho-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
rho-contract = { path = "../../contract" }
rho-operation = { path = "../../operation" }
rho-execution = { path = "../../execution" }
rho-remote-owner = { path = "../../../plugins/remote/backend/owner" }
tokio.workspace = true
