[package]
name = "rho-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
rho-contract = { path = "../../contract" }
rho-operation = { path = "../../operation" }
rho-execution = { path = "../../execution" }
rho-process = { path = "../process" }
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
