// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileObservation = { path: string, kind: string, sha256: string | null, byte_size: number, mode: number | null, modified_at_ns: string | null, };
