// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSnapshot } from "./ProjectSnapshot.js";

export type ProjectPatchRecovery = { project_root: string, before: ProjectSnapshot, affected_paths: Array<string>, } | { action: string, root: string, affected_paths: Array<string>, };
