// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capacity of the filesystem containing the canonical project root, not project size.
 */
export type ProjectStorage = { project: string, free_bytes: number, total_bytes: number, available_bytes: number, observed_at_ms: number, };
