// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileObservation } from "./FileObservation.js";
import type { GitObservation } from "./GitObservation.js";

export type ProjectSnapshot = { root: string, git: GitObservation | null, files: Array<FileObservation>, entries: Array<string>, entries_truncated: boolean, observed_at_ms: number, };
