// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadFileArguments = { path: string, offset: number, limit_bytes: number, expected_sha256: string | null, };
