// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextCursor } from "./TextCursor.js";

export type ReadTextArguments = { path: string, expected_sha256: string | null, start_line: number, limit_lines: number, continuation: TextCursor | null, };
