// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchTextCursor } from "./SearchTextCursor.js";

export type SearchTextArguments = {
/**
 * Literal UTF-8 text. Case-insensitive matching uses Unicode lowercase mapping (not locale-specific collation).
 */
text: string, case_sensitive: boolean, directory: string,
/**
 * Literal substring of the file name (same case rule as text).
 */
filename_contains: string | null, show_hidden: boolean, limit_matches: number, continuation: SearchTextCursor | null, };
