// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectoryScanFrame } from "./DirectoryScanFrame.js";
import type { TextCursor } from "./TextCursor.js";

export type SearchTextCursor = { project: string, query_sha256: string, directories: Array<DirectoryScanFrame>, active_file: TextCursor | null, };
