// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchFilesCursor } from "./SearchFilesCursor.js";

export type SearchFilesArguments = { continuation: SearchFilesCursor | null, text: string, show_hidden: boolean, };
