// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchTextCursor } from "./SearchTextCursor.js";
import type { TextMatch } from "./TextMatch.js";
import type { TextSkip } from "./TextSkip.js";

export type SearchTextPage = { matches: Array<TextMatch>, skipped: Array<TextSkip>, scanned_entries: number,
/**
 * Bytes examined for literal matches, distinct from full-file identity verification.
 */
scanned_bytes: number,
/**
 * Bytes of successfully loaded files verified on this page, including cached reads.
 */
verified_bytes: number, continuation: SearchTextCursor | null,
/**
 * Pagination is exhausted. Skipped content remains unavailable and is not claimed as read.
 */
complete: boolean, limit_reason: string | null, consistency: string, };
