// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextSkipReason } from "./TextSkipReason.js";

export type TextSkip = { path: string, reason: TextSkipReason, detail: string, };
