// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadTextArguments } from "./ReadTextArguments.js";
import type { TextIdentity } from "./TextIdentity.js";

export type TextMatch = { file: TextIdentity, line: number, byte_start: number, byte_end: number, snippet: string, read: ReadTextArguments, };
