// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextIdentity } from "./TextIdentity.js";

export type TextCursor = { project: string, file: TextIdentity, byte_offset: number, line: number, };
