// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextCursor } from "./TextCursor.js";
import type { TextFragment } from "./TextFragment.js";
import type { TextIdentity } from "./TextIdentity.js";
import type { TextSkip } from "./TextSkip.js";

export type TextPage = { file: TextIdentity | null, fragments: Array<TextFragment>, skipped: TextSkip | null, continuation: TextCursor | null,
/**
 * Pagination is exhausted. Skipped content remains unavailable and is not claimed as read.
 */
complete: boolean, limit_reason: string | null, };
