import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const mode = process.argv[2] ?? "check";
assert.ok(
  ["generate", "build", "check"].includes(mode),
  "expected generate, build or check",
);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "rho-next-client-"));
function files(dir, prefix = "") {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => {
      const name = path.join(prefix, entry.name);
      return entry.isDirectory()
        ? files(path.join(dir, entry.name), name)
        : [name];
    })
    .sort();
}
try {
  const html = fs.readFileSync(
    path.join(root, "workbench/assets/index.html"),
    "utf8",
  );
  const source = fs.readFileSync(path.join(root, "ui/src/app.ts"), "utf8");
  const ids = [...html.matchAll(/\bid="([^"]+)"/gu)].map((match) => match[1]);
  assert.equal(ids.length, new Set(ids).size, "duplicate client element id");
  for (const match of source.matchAll(
    /(?:el(?:<[^>]+>)?|button|display)\s*\(\s*"([^"]+)"/gu,
  )) {
    assert.ok(
      ids.includes(match[1]),
      `client references missing element: ${match[1]}`,
    );
  }
  assert.equal(
    [...html.matchAll(/<script\b/gu)].length,
    1,
    "client must have one embedded entry script",
  );
  assert.ok(html.includes('src="/app.js"'));
  assert.ok(
    !/\b(?:src|href)="https?:/u.test(html),
    "local workbench must not load third-party assets",
  );
  if (mode !== "build") {
    const generated = path.join(temp, "types");
    execFileSync(
      "cargo",
      [
        "run",
        "--manifest-path",
        path.join(root, "..", "Cargo.toml"),
        "-p",
        "rho-next-contract",
        "--bin",
        "export-client",
        "--locked",
        "--offline",
        "--",
        generated,
      ],
      { stdio: "inherit" },
    );
    const committed = path.join(root, "ui/src/generated");
    const names = files(generated);
    if (mode === "check")
      assert.deepEqual(
        files(committed),
        names,
        "generated type inventory changed; run npm run generate --prefix next/ui",
      );
    for (const name of names) {
      const target = path.join(committed, name);
      if (mode === "generate") {
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.copyFileSync(path.join(generated, name), target);
      } else
        assert.equal(
          fs.readFileSync(target, "utf8"),
          fs.readFileSync(path.join(generated, name), "utf8"),
          `stale binding: ${name}`,
        );
    }
    // Retire only known generated files that no longer have a Rust owner.
    if (mode === "generate")
      for (const name of files(committed)) {
        if (!names.includes(name)) {
          const target = path.join(committed, name);
          assert.ok(
            fs
              .readFileSync(target, "utf8")
              .startsWith("// This file was generated by [ts-rs]"),
          );
          fs.unlinkSync(target);
        }
      }
  }
  if (mode !== "generate") {
    const output = path.join(temp, "js");
    execFileSync(
      process.execPath,
      [
        path.join(root, "ui/node_modules/typescript/bin/tsc"),
        "-p",
        path.join(root, "ui/tsconfig.json"),
        "--outDir",
        output,
      ],
      { stdio: "inherit" },
    );
    const javascript = fs.readFileSync(path.join(output, "app.js"), "utf8");
    assert.ok(
      !/^\s*import\s/mu.test(javascript),
      "embedded app unexpectedly needs additional runtime modules",
    );
    const target = path.join(root, "workbench/assets/app.js");
    if (mode === "build") fs.writeFileSync(target, javascript);
    else
      assert.equal(
        fs.readFileSync(target, "utf8"),
        javascript,
        "embedded app.js is stale; run npm run build --prefix next/ui",
      );
  }
  console.log(
    `Next client ${mode}: generated Rust contract and embedded client agree.`,
  );
} finally {
  fs.rmSync(temp, { recursive: true, force: true });
}
