// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceState = "preparing" | "active" | "draining" | "released" | "failed" | "cleanup_failed" | "disconnected";
