// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKey } from "./CapabilityKey.js";
import type { RequestId } from "./RequestId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Every request crosses the containing shell's scoped Host port. No browser
 * credential, project root or user identity is accepted from the iframe.
 */
export type PluginViewRequest = { "type": "query", capability: CapabilityKey, arguments: JsonValue, } | { "type": "invoke", request_id: RequestId, capability: CapabilityKey, arguments: JsonValue, preconditions: Array<JsonValue>, } | { "type": "get_operation", operation_id: string, } | { "type": "cancel", operation_id: string, } | { "type": "set_state", expected_version: number, state: JsonValue, };
