// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId.js";
import type { InstanceAlias } from "./InstanceAlias.js";
import type { PluginId } from "./PluginId.js";
import type { RevisionId } from "./RevisionId.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ScenarioInstance = { plugin: PluginId, revision: RevisionId, artifact: ArtifactId, configuration: JsonValue, dependencies: { [key in InstanceAlias]: InstanceAlias }, };
