// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceAlias } from "./InstanceAlias.js";
import type { PluginInstanceId } from "./PluginInstanceId.js";
import type { PrincipalId } from "./PrincipalId.js";
import type { ProjectId } from "./ProjectId.js";
import type { ScenarioRevisionId } from "./ScenarioRevisionId.js";
import type { WindowId } from "./WindowId.js";

export type WindowScenario = { window: WindowId, project: ProjectId, principal: PrincipalId, revision: ScenarioRevisionId, instances: { [key in InstanceAlias]: PluginInstanceId }, };
