[package]
name = "rho-agents"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rho-agent-engine = { path = "../../plugins/agent/backend/engine" }
rho-application = { path = "../application" }
rho-contract = { path = "../contract" }
async-trait.workspace = true
serde_json.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tokio.workspace = true
