import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const mode = process.argv[2] ?? "check";
assert.ok(
  ["generate", "build", "check"].includes(mode),
  "expected generate, build or check",
);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "rho-client-"));
function files(dir, prefix = "") {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => {
      const name = path.join(prefix, entry.name);
      return entry.isDirectory()
        ? files(path.join(dir, entry.name), name)
        : [name];
    })
    .sort();
}
try {
  if (mode !== "build") {
    const generated = path.join(temp, "types");
    execFileSync(
      "cargo",
      [
        "run",
        "--manifest-path",
        path.join(root, "Cargo.toml"),
        "-p",
        "rho-contract",
        "--bin",
        "export-client",
        "--locked",
        "--offline",
        "--",
        generated,
      ],
      { stdio: "inherit" },
    );
    const committed = path.join(root, "ui/src/generated");
    const names = files(generated);
    if (mode === "check")
      assert.deepEqual(
        files(committed),
        names,
        "generated type inventory changed; run npm run generate --prefix ui",
      );
    for (const name of names) {
      const target = path.join(committed, name);
      if (mode === "generate") {
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.copyFileSync(path.join(generated, name), target);
      } else
        assert.equal(
          fs.readFileSync(target, "utf8"),
          fs.readFileSync(path.join(generated, name), "utf8"),
          `stale binding: ${name}`,
        );
    }
    // Retire only known generated files that no longer have a Rust owner.
    if (mode === "generate")
      for (const name of files(committed)) {
        if (!names.includes(name)) {
          const target = path.join(committed, name);
          assert.ok(
            fs
              .readFileSync(target, "utf8")
              .startsWith("// This file was generated by [ts-rs]"),
          );
          fs.unlinkSync(target);
        }
      }
  }
  if (mode !== "generate") {
    execFileSync(process.execPath, [path.join(root, "ui/node_modules/typescript/bin/tsc"), "-p", path.join(root, "ui/tsconfig.json"), "--noEmit"], { stdio: "inherit" });
    const output = path.join(temp, "assets");
    const { build } = await import("../ui/node_modules/vite/dist/node/index.js");
    await build({ configFile: path.join(root, "ui/vite.config.ts"), build: { outDir: output, watch: null } });
    fs.copyFileSync(path.join(root, "ui/index.html"), path.join(output, "index.html"));
    const html = fs.readFileSync(path.join(output, "index.html"), "utf8");
    assert.ok(html.includes('src="/app.js"') && html.includes('href="/style.css"'));
    assert.ok(!/\b(?:src|href)="https?:/u.test(html), "workbench must use local assets");
    const committed = path.join(root, "crates/workbench/assets");
    const names = files(output);
    assert.deepEqual(names, ["app.js", "index.html", "style.css"], "embedded asset inventory changed");
    if (mode === "check") assert.deepEqual(files(committed), names);
    for (const name of names) {
      if (mode === "build") fs.copyFileSync(path.join(output, name), path.join(committed, name));
      else assert.ok(fs.readFileSync(path.join(output,name)).equals(fs.readFileSync(path.join(committed,name))), `stale embedded asset: ${name}; run npm run build --prefix ui`);
    }
  }
  console.log(
    `Next client ${mode}: generated Rust contract and embedded client agree.`,
  );
} finally {
  fs.rmSync(temp, { recursive: true, force: true });
}
