#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { pathMatchesPattern } from "./path-ownership.mjs";

const REGISTRY_FILE = "governance/registry.json";
const SOURCE_MAP_FILE = "governance/source-map.json";
const INDEX_FILE = "docs/INDEX.md";
const SOURCE_INDEX_FILE = "docs/SOURCE-INDEX.md";
const NOTICE = "<!-- Generated by scripts/governance.mjs from governance/*.json. -->";
const SCRIPT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const compare = (left, right) => String(left) < String(right) ? -1 : String(left) > String(right) ? 1 : 0;
const uniqueSorted = (values) => [...new Set(values)].sort(compare);
const isObject = (value) => value != null && typeof value === "object" && !Array.isArray(value);
const normalizePath = (value) => value.split(path.sep).join("/").replace(/^\.\//u, "");
const defaultRoot = () => fs.existsSync(path.join(process.cwd(), REGISTRY_FILE)) ? process.cwd() : SCRIPT_ROOT;

export class DocumentationMapError extends Error {
  constructor(errors) {
    const messages = uniqueSorted(errors);
    super(`Documentation map validation failed:\n${messages.map((item) => `- ${item}`).join("\n")}`);
    this.name = "DocumentationMapError";
    this.errors = messages;
  }
}

function readJson(root, file) {
  try {
    return JSON.parse(fs.readFileSync(path.join(root, file), "utf8"));
  } catch (error) {
    const detail = error.code === "ENOENT" ? "file is missing" : `invalid JSON: ${error.message}`;
    throw new DocumentationMapError([`${file}: ${detail}`]);
  }
}

function requireShape(value, fields, label, errors) {
  if (!isObject(value)) {
    errors.push(`${label} must be an object`);
    return false;
  }
  for (const field of fields) if (!Object.hasOwn(value, field)) errors.push(`${label}: missing field ${field}`);
  for (const field of Object.keys(value)) if (!fields.includes(field)) errors.push(`${label}: unknown field ${field}`);
  return true;
}

function stringList(value, label, errors, { unique = true, sort = true } = {}) {
  if (!Array.isArray(value)) {
    errors.push(`${label} must be an array`);
    return [];
  }
  const strings = value.filter((item, index) => {
    if (typeof item === "string" && item.length > 0) return true;
    errors.push(`${label}[${index}] must be a non-empty string`);
    return false;
  });
  if (unique) for (const item of new Set(strings)) {
    if (strings.filter((candidate) => candidate === item).length > 1) errors.push(`${label} contains duplicate value ${item}`);
  }
  return sort ? uniqueSorted(strings) : strings;
}

function validRepoPath(value) {
  const normalized = typeof value === "string" ? normalizePath(value) : "";
  return normalized.length > 0 && normalized === value && !path.isAbsolute(value) &&
    !value.split("/").some((part) => part === "" || part === "." || part === "..");
}

function validateRegistry(registry, root, errors) {
  if (!requireShape(registry, ["schema_version", "pages"], REGISTRY_FILE, errors)) return [];
  if (registry.schema_version !== 1) errors.push(`${REGISTRY_FILE}: schema_version must be 1`);
  if (!Array.isArray(registry.pages)) {
    errors.push(`${REGISTRY_FILE}: pages must be an array`);
    return [];
  }
  const pages = [];
  registry.pages.forEach((page, index) => {
    const label = `${REGISTRY_FILE}: pages[${index}]`;
    if (!requireShape(page, ["id", "title", "document", "area"], label, errors)) return;
    for (const field of ["id", "title", "area"]) {
      if (typeof page[field] !== "string" || page[field].length === 0) errors.push(`${label}.${field} must be a non-empty string`);
    }
    if (!validRepoPath(page.document) || !/^docs\/.+\.md$/u.test(page.document)) {
      errors.push(`${label}.document must name a repository-relative Markdown file below docs/`);
    } else if (!fs.existsSync(path.join(root, page.document))) {
      errors.push(`${label}.document does not exist: ${page.document}`);
    }
    pages.push({ id: page.id, title: page.title, document: page.document, area: page.area });
  });
  for (const field of ["id", "document"]) {
    const values = pages.map((page) => page[field]);
    for (const value of new Set(values)) {
      if (values.filter((candidate) => candidate === value).length > 1) errors.push(`${REGISTRY_FILE}: duplicate page ${field} ${value}`);
    }
  }
  return pages.sort((left, right) => compare(left.id, right.id));
}

function validateSourceMap(sourceMap, errors) {
  if (!requireShape(sourceMap, ["schema_version", "checks", "areas"], SOURCE_MAP_FILE, errors)) {
    return { checks: [], areas: [] };
  }
  if (sourceMap.schema_version !== 1) errors.push(`${SOURCE_MAP_FILE}: schema_version must be 1`);
  const checks = [];
  if (!isObject(sourceMap.checks)) errors.push(`${SOURCE_MAP_FILE}: checks must be an object`);
  else for (const [id, check] of Object.entries(sourceMap.checks)) {
    const label = `${SOURCE_MAP_FILE}: checks.${id}`;
    if (!requireShape(check, ["command"], label, errors)) continue;
    const command = stringList(check.command, `${label}.command`, errors, { unique: false, sort: false });
    if (command.length === 0) errors.push(`${label}.command must not be empty`);
    checks.push({ id, command });
  }
  const areas = [];
  if (!isObject(sourceMap.areas)) errors.push(`${SOURCE_MAP_FILE}: areas must be an object`);
  else for (const [id, area] of Object.entries(sourceMap.areas)) {
    const label = `${SOURCE_MAP_FILE}: areas.${id}`;
    if (!requireShape(area, ["sources", "checks"], label, errors)) continue;
    const sources = stringList(area.sources, `${label}.sources`, errors);
    for (const source of sources) if (!validRepoPath(source)) errors.push(`${label}.sources contains invalid path ${source}`);
    areas.push({ id, sources, checks: stringList(area.checks, `${label}.checks`, errors) });
  }
  return {
    checks: checks.sort((left, right) => compare(left.id, right.id)),
    areas: areas.sort((left, right) => compare(left.id, right.id)),
  };
}

function repositoryFiles(directory, root = directory) {
  const files = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if ([".git", "node_modules", "target"].includes(entry.name)) continue;
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...repositoryFiles(file, root));
    else if (entry.isFile()) files.push(normalizePath(path.relative(root, file)));
  }
  return files;
}

export function loadDocumentationMap(root = defaultRoot()) {
  const resolved = path.resolve(root);
  return { root: resolved, registry: readJson(resolved, REGISTRY_FILE), sourceMap: readJson(resolved, SOURCE_MAP_FILE) };
}

export function validateDocumentationMap(root = defaultRoot()) {
  const loaded = loadDocumentationMap(root);
  const errors = [];
  const pages = validateRegistry(loaded.registry, loaded.root, errors);
  const { checks, areas } = validateSourceMap(loaded.sourceMap, errors);
  const areaIds = new Set(areas.map((area) => area.id));
  const checkIds = new Set(checks.map((check) => check.id));
  for (const page of pages) if (!areaIds.has(page.area)) errors.push(`${page.id}.area references unknown area ${page.area}`);
  for (const area of areas) for (const check of area.checks) {
    if (!checkIds.has(check)) errors.push(`${area.id}.checks references unknown check ${check}`);
  }
  const files = repositoryFiles(loaded.root);
  for (const area of areas) for (const pattern of area.sources) {
    if (!files.some((file) => pathMatchesPattern(file, pattern))) {
      errors.push(`${SOURCE_MAP_FILE}: areas.${area.id}.sources pattern matches no file: ${pattern}`);
    }
  }
  if (errors.length > 0) throw new DocumentationMapError(errors);
  return {
    root: loaded.root,
    pages,
    pageById: new Map(pages.map((page) => [page.id, page])),
    checks,
    checkById: new Map(checks.map((check) => [check.id, check])),
    areas,
    areaById: new Map(areas.map((area) => [area.id, area])),
  };
}

const documentLink = (document) => `<${path.posix.relative("docs", document)}>`;
const title = (value) => value.replace(/([\\[\]])/gu, "\\$1");
const shellDisplay = (command) => command.map((argument) => /^[A-Za-z0-9_./:@%+=,-]+$/u.test(argument)
  ? argument
  : `'${argument.replace(/'/gu, `'"'"'`)}'`).join(" ");

export function renderDocumentationIndex(context) {
  const lines = [NOTICE, "", "# Documentation Index", "", `Generated from \`${REGISTRY_FILE}\`. Edit the JSON source and regenerate.`, ""];
  for (const area of context.areas) {
    const pages = context.pages.filter((page) => page.area === area.id);
    if (pages.length === 0) continue;
    lines.push(`## \`${area.id}\``, "");
    for (const page of pages) lines.push(`- [${title(page.title)}](${documentLink(page.document)}) — \`${page.id}\``);
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderSourceIndex(context) {
  const lines = [NOTICE, "", "# Source Index", "", `Generated from \`${SOURCE_MAP_FILE}\` and \`${REGISTRY_FILE}\`. Edit the JSON sources and regenerate.`, ""];
  for (const area of context.areas) {
    const pages = context.pages.filter((page) => page.area === area.id);
    lines.push(`## \`${area.id}\``, "", "Documentation:", "");
    if (pages.length === 0) lines.push("- None.");
    else for (const page of pages) lines.push(`- [${title(page.title)}](${documentLink(page.document)}) — \`${page.id}\``);
    lines.push("", "Sources:", "", ...area.sources.map((source) => `- \`${source}\``), "", "Checks:", "");
    if (area.checks.length === 0) lines.push("- None.");
    else for (const id of area.checks) {
      const check = context.checkById.get(id);
      lines.push(`- \`${id}\`: \`${JSON.stringify(check.command).replace(/`/gu, "\\`")}\``);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function generated(context) {
  return new Map([[INDEX_FILE, renderDocumentationIndex(context)], [SOURCE_INDEX_FILE, renderSourceIndex(context)]]);
}

export function generateDocumentationIndexes(root = defaultRoot()) {
  const context = validateDocumentationMap(root);
  const files = generated(context);
  for (const [name, content] of files) fs.writeFileSync(path.join(context.root, name), content);
  return { context, generated: [...files.keys()] };
}

export function checkDocumentationIndexes(root = defaultRoot()) {
  const context = validateDocumentationMap(root);
  const errors = [];
  for (const [name, expected] of generated(context)) {
    const file = path.join(context.root, name);
    if (!fs.existsSync(file)) errors.push(`${name}: generated file is missing; run governance generate`);
    else if (fs.readFileSync(file, "utf8") !== expected) errors.push(`${name}: generated file is stale; run governance generate`);
  }
  if (errors.length > 0) throw new DocumentationMapError(errors);
  return context;
}

export function documentationImpact(context, changed) {
  const files = uniqueSorted(changed.map(normalizePath));
  const areaIds = new Set();
  const unmapped = [];
  for (const file of files) {
    const matched = context.areas.filter((area) => area.sources.some((pattern) => pathMatchesPattern(file, pattern)));
    if (matched.length === 0) unmapped.push(file);
    else for (const area of matched) areaIds.add(area.id);
  }
  const areas = [...areaIds].sort(compare);
  const pages = context.pages.filter((page) => areaIds.has(page.area)).map((page) => page.id).sort(compare);
  const ids = new Set(areas.flatMap((area) => context.areaById.get(area).checks));
  const checks = [...ids].sort(compare).map((id) => ({ id, command: [...context.checkById.get(id).command] }));
  return { changed: files, areas, pages, checks, unmapped };
}

function changedFiles(root) {
  const result = spawnSync("git", ["status", "--porcelain=v1", "--untracked-files=all", "--no-renames", "-z"], {
    cwd: root,
    encoding: "utf8",
  });
  if (result.status !== 0) throw new DocumentationMapError(["--changed-auto requires a Git worktree"]);
  return result.stdout.split("\0").filter((entry) => entry.length > 3).map((entry) => entry.slice(3));
}

const USAGE = "Usage: node scripts/governance.mjs <check|generate|impact> [--json] [--root <repository>]";

function parseArguments(argv) {
  const command = argv[0];
  if (!["check", "generate", "impact"].includes(command)) throw new DocumentationMapError([USAGE]);
  const options = { root: defaultRoot(), json: false, changed: [], changedAuto: false };
  for (let index = 1; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--json") options.json = true;
    else if (argument === "--changed-auto") options.changedAuto = true;
    else if (argument === "--root") {
      if (argv[index + 1] == null) throw new DocumentationMapError(["--root requires a value"]);
      options.root = path.resolve(argv[++index]);
    } else if (argument === "--changed") {
      const before = options.changed.length;
      while (argv[index + 1] != null && !argv[index + 1].startsWith("--")) options.changed.push(argv[++index]);
      if (options.changed.length === before) throw new DocumentationMapError(["--changed requires at least one path"]);
    } else throw new DocumentationMapError([`Unknown argument: ${argument}`, USAGE]);
  }
  if (command !== "impact" && (options.changedAuto || options.changed.length > 0)) {
    throw new DocumentationMapError([`${command} does not accept changed-path options`]);
  }
  if (command === "impact" && options.changedAuto === (options.changed.length > 0)) {
    throw new DocumentationMapError([options.changedAuto
      ? "impact accepts either --changed-auto or --changed, not both"
      : "impact requires --changed-auto or --changed <path>..."]);
  }
  return { command, options };
}

function emit(value, options, human) {
  process.stdout.write(options.json ? `${JSON.stringify(value, null, 2)}\n` : human(value));
}

export function runCli(argv = process.argv.slice(2)) {
  const { command, options } = parseArguments(argv);
  if (command === "check") {
    const context = checkDocumentationIndexes(options.root);
    emit({ valid: true, pages: context.pages.length, areas: context.areas.length, checks: context.checks.length,
      generated: [INDEX_FILE, SOURCE_INDEX_FILE] }, options,
    (value) => `Documentation map valid: ${value.pages} pages, ${value.areas} areas, ${value.checks} checks; generated indexes match their inputs.\n`);
  } else if (command === "generate") {
    const result = generateDocumentationIndexes(options.root);
    emit({ generated: result.generated, pages: result.context.pages.length, areas: result.context.areas.length }, options,
      (value) => `Generated documentation indexes:\n${value.generated.map((file) => `- ${file}`).join("\n")}\n`);
  } else {
    const context = validateDocumentationMap(options.root);
    const impact = documentationImpact(context, options.changedAuto ? changedFiles(context.root) : options.changed);
    emit(impact, options, (value) => {
      const lines = [`Changed: ${value.changed.length}`, `Areas: ${value.areas.join(", ") || "none"}`,
        `Pages: ${value.pages.join(", ") || "none"}`, "Checks:"];
      lines.push(...(value.checks.length === 0 ? ["  none"] : value.checks.map((check) => `  ${check.id}: ${shellDisplay(check.command)}`)));
      lines.push("Unmapped:", ...(value.unmapped.length === 0 ? ["  none"] : value.unmapped.map((file) => `  ${file}`)));
      return `${lines.join("\n")}\n`;
    });
  }
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  try {
    runCli();
  } catch (error) {
    const errors = error instanceof DocumentationMapError ? error.errors : [error.message ?? String(error)];
    process.stderr.write(process.argv.includes("--json")
      ? `${JSON.stringify({ valid: false, errors }, null, 2)}\n`
      : `documentation-map: validation failed:\n${errors.map((item) => `- ${item}`).join("\n")}\n`);
    process.exitCode = 1;
  }
}
