args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) args[[1L]] else getwd()
bridge <- new.env(parent = asNamespace("utils")); bridge$can_inspect_bindings <- requireNamespace("rlang", quietly = TRUE)
stopifnot(bridge$can_inspect_bindings, requireNamespace("jsonlite", quietly = TRUE))
for (file in c("query.R", "objects.R", "dispatch.R")) sys.source(file.path(root, "plugins/r/backend/engine/r/bridge", file), bridge)
local({
  modifyList <- function(x, y, keep.null = TRUE) { x[names(y)] <- y; x }
  scope <- list(project = "/isolated", principal = "test", session = "test-session")
  list_args <- function(...) modifyList(list(expected_session = "test-session", name_contains = "fixture_", object_type = NULL, directory_ref = NULL, offset = 0L, limit = 200L, scope = scope), list(...), keep.null = TRUE)
  observe <- function(name, path = list()) bridge$rho_observe_object(list(name = name, path = path, scope = scope))
  read <- function(ref, kind = "values", ...) bridge$rho_read_object(modifyList(list(object_ref = ref, kind = kind, path = list(), start = 1L, limit = 200L, column_start = 1L, column_limit = 50L, text_start = 1L, text_limit_bytes = 65536L, scope = scope), list(...), keep.null = TRUE))
  fails <- function(code, label) { error <- tryCatch({ force(code); NULL }, error = identity); stopifnot(inherits(error, "error"), grepl(label, conditionMessage(error), fixed = TRUE)) }
  for (i in seq_len(10001)) assign(sprintf("fixture_%05d", i), i, .GlobalEnv)
  page <- bridge$rho_list_objects(list_args()); names <- vapply(page$entries, `[[`, "", "name"); id <- page$directory_ref
  while (!is.null(page$next_offset)) { page <- bridge$rho_list_objects(list_args(directory_ref = id, offset = page$next_offset)); names <- c(names, vapply(page$entries, `[[`, "", "name")) }
  stopifnot(length(names) == 10001L, !anyDuplicated(names), page$complete)
  fails(bridge$rho_list_objects(list_args(directory_ref = id, name_contains = "changed")), "observation_invalid")
  assign("fixture_00001", "changed", .GlobalEnv)
  fails(bridge$rho_list_objects(list_args(directory_ref = id)), "content_changed")
  rm(list = ls(.GlobalEnv, pattern = "^fixture_"), envir = .GlobalEnv)
  bridge$rho_invalidate_objects()
  assign("fixture_table", data.frame(a = 1:501, b = seq_len(501), text = rep(paste(rep("界", 1000), collapse = ""), 501)), .GlobalEnv)
  object <- observe("fixture_table"); page <- read(object$object_ref, "table", start = 401, column_start = 2)
  stopifnot(page$columns[[1L]]$values[[1L]]$number == 401, page$next_start > 401, page$columns[[2L]]$values[[1L]]$next_text_start > 1)
  text <- read(object$object_ref, "text", path = list(list(kind = "index", index = 3L)), start = 401, text_start = 101)
  stopifnot(nchar(text$values[[1L]]$text) == 900)
  assign("fixture_list", list(a = list(1:500, rep("long", 300)), repeated = 1, repeated = 2), .GlobalEnv)
  object <- observe("fixture_list")
  fails(read(object$object_ref, path = list(list(kind = "name", name = "repeated"))), "invalid_path")
  page <- read(object$object_ref, path = list(list(kind = "index", index = 1L), list(kind = "index", index = 1L)), start = 301)
  stopifnot(length(page$values) == 200, page$values[[1L]]$number == 301)
  assign("fixture_matrix", matrix(seq_len(12000), nrow = 300L, ncol = 40L), .GlobalEnv)
  matrix_object <- observe("fixture_matrix")
  matrix_page <- read(matrix_object$object_ref, "table", start = 251L, column_start = 30L)
  stopifnot(length(matrix_page$columns) == 11L, matrix_page$columns[[1L]]$values[[1L]]$number == 8951,
            sum(vapply(matrix_page$columns, function(x) length(x$values), 1L)) <= 2000L)
  assign("fixture_text_matrix", matrix(rep(paste(rep("界", 1000), collapse = ""), 4L), nrow = 2L), .GlobalEnv)
  text_matrix <- observe("fixture_text_matrix")
  text_matrix_page <- read(text_matrix$object_ref, "table", start = 2L, column_start = 2L)
  continued_matrix <- read(text_matrix$object_ref, "text", start = 2L + (2L - 1L) * 2L, text_start = text_matrix_page$columns[[1L]]$values[[1L]]$next_text_start)
  stopifnot(is.null(continued_matrix$next_text_start), nchar(continued_matrix$values[[1L]]$text) > 0L)
  assign("fixture_named", setNames("value", paste(rep("名", 1000), collapse = "")), .GlobalEnv)
  named_object <- observe("fixture_named")
  named_page <- read(named_object$object_ref, "names")
  stopifnot(named_page$values[[1L]]$next_text_start > 1)
  named_text <- read(named_object$object_ref, "text", text_attribute = "names", text_start = named_page$values[[1L]]$next_text_start)
  stopifnot(!is.null(named_text$values[[1L]]$text))
  fails(read(named_object$object_ref, "text", text_attribute = "names", text_limit_bytes = 1L), "budget_exhausted")
  assign("fixture_units", as.difftime(1:3, units = "hours"), .GlobalEnv)
  stopifnot(observe("fixture_units")$metadata$attributes[[1L]]$values[[1L]] == "hours")
  assign("fixture_special", c(NA_real_, NaN, Inf, -Inf, 4), .GlobalEnv)
  page <- read(observe("fixture_special")$object_ref)
  stopifnot(identical(vapply(page$values, `[[`, "", "kind"), c("missing", "non_finite", "non_finite", "non_finite", "value")))
  assign("fixture_factor", factor(c("a", "b", NA)), .GlobalEnv)
  page <- read(observe("fixture_factor")$object_ref, "levels")
  stopifnot(page$values[[2L]]$text == "b")
  assign("fixture_date", as.Date("2020-01-01") + 0:1000, .GlobalEnv)
  assign("length.Date", function(...) stop("USER LENGTH CALLED"), .GlobalEnv)
  page <- read(observe("fixture_date")$object_ref, start = 500)
  stopifnot(length(page$values) == 200)
  delayedAssign("fixture_promise", stop("PROMISE FORCED"), assign.env = .GlobalEnv)
  makeActiveBinding("fixture_active", function(...) stop("ACTIVE BINDING CALLED"), .GlobalEnv)
  assign("fixture_custom", structure(1:5, class = "hostile"), .GlobalEnv)
  assign("print.hostile", function(...) stop("USER METHOD CALLED"), .GlobalEnv)
  stopifnot(observe("fixture_promise")$metadata$kind == "promise", observe("fixture_active")$metadata$kind == "active_binding", identical(observe("fixture_custom")$metadata$supported_reads, list("structure")))
  for (name in c("fixture_promise", "fixture_active", "fixture_custom")) {
    safe <- observe(name)
    structure <- read(safe$object_ref, "structure")
    stopifnot(structure$root_name == name, identical(structure$observed_path, list()), structure$metadata$kind == safe$metadata$kind)
    fails(read(safe$object_ref, "values"), "unsupported")
  }
  nested_path <- list(list(kind = "index", index = 1L), list(kind = "index", index = 1L))
  nested <- observe("fixture_list", nested_path)
  nested_page <- read(nested$object_ref, "values", start = 301L)
  stopifnot(nested_page$root_name == "fixture_list", identical(nested_page$observed_path, nested_path), nested_page$values[[1L]]$number == 301L)
  object <- observe("fixture_date")
  fails(read(object$object_ref, scope = modifyList(scope, list(principal = "other"))), "observation_invalid")
  bridge$rho_object_state$handles[[object$object_ref]]$used <- bridge$rho_object_now() - 60001
  fails(read(object$object_ref), "observation_expired")
  object <- observe("fixture_date")
  bridge$rho_object_state$handles[[object$object_ref]]$created <- bridge$rho_object_now() - 300001
  fails(read(object$object_ref), "observation_expired")
  object <- observe("fixture_date")
  result <- bridge$rho_dispatch(list(protocol_version = 1L, request_id = "failed", action = "execute", payload = list(code = "stop('intended failure')")))
  stopifnot(result$outcome == "failed")
  fails(read(object$object_ref), "observation_expired")
  bridge$rho_invalidate_objects()
  for (i in 1:32) observe("fixture_date")
  fails(observe("fixture_date"), "budget_exhausted")
  rm(list = ls(.GlobalEnv, pattern = "^fixture_|^length.Date$|^print.hostile$"), envir = .GlobalEnv)
})
cat("R object progressive inspection checks passed\n")

# The cached startup flag cannot authorize reading a value after the provider was unloaded.
local({
  bridge$rho_invalidate_objects()
  stopifnot(isTRUE(bridge$can_inspect_bindings), !is.null(base::.Internal(getRegisteredNamespace("rlang"))))
  scope <- list(project = "/isolated", principal = "test", session = "native")
  payload <- function(name) list(expected_session = "native", name = name, path = list(), scope = scope)
  dispatch <- function(action, value) bridge$rho_dispatch(list(protocol_version = 1L, request_id = "provider-test", action = action, payload = value))
  event <- base::packageEvent("rlang", "onLoad"); previous <- base::getHook(event); loads <- 0L; effects <- 0L
  base::assign("fixture_provider_value", 1:3, .GlobalEnv)
  base::assign("fixture_provider_empty", NULL, .GlobalEnv)
  base::delayedAssign("fixture_provider_promise", { effects <<- effects + 1L; stop("Promise was forced") }, assign.env = .GlobalEnv)
  base::makeActiveBinding("fixture_provider_active", function(...) { effects <<- effects + 1L; stop("Active binding was invoked") }, .GlobalEnv)
  empty <- bridge$rho_observe_object(payload("fixture_provider_empty")); stopifnot(empty$metadata$length == 0L)
  on.exit({ base::setHook(event, previous, action = "replace"); base::loadNamespace("rlang"); base::rm(list = base::ls(.GlobalEnv, pattern = "^fixture_provider_"), envir = .GlobalEnv); bridge$rho_invalidate_objects() }, add = TRUE)
  base::setHook(event, function(...) { loads <<- loads + 1L }, action = "append")
  base::unloadNamespace("rlang")
  before <- base::sort(base::loadedNamespaces())
  for (name in c("fixture_provider_value", "fixture_provider_empty", "fixture_provider_promise")) {
    response <- dispatch("observe_object", payload(name))
    stopifnot(response$outcome == "failed", response$value$query_error$code == "unavailable", grepl("rlang is not loaded", response$error, fixed = TRUE))
    shallow <- dispatch("inspect_object", list(name = name, max_items = 5L))
    stopifnot(shallow$outcome == "failed", shallow$value$query_error$code == "unavailable")
  }
  active <- dispatch("observe_object", payload("fixture_provider_active"))
  stopifnot(active$outcome == "succeeded", active$value$metadata$kind == "active_binding", bridge$rho_binding_summary("fixture_provider_active")$kind == "active_binding", bridge$rho_object_binding("fixture_provider_missing")$kind == "missing")
  directory <- dispatch("list_objects", list(expected_session = "native", name_contains = "fixture_provider_absent_", object_type = NULL, directory_ref = NULL, offset = 0L, limit = 20L, scope = scope))
  stopifnot(directory$outcome == "succeeded", directory$value$total == 0L, directory$value$complete, effects == 0L, loads == 0L, isTRUE(bridge$can_inspect_bindings), is.null(base::.Internal(getRegisteredNamespace("rlang"))), identical(before, base::sort(base::loadedNamespaces())))
})

# Exercise the production serializer gate after unloading jsonlite; no decoder or query runs.
local({
  event <- base::packageEvent("jsonlite", "onLoad"); previous <- base::getHook(event); loads <- 0L; masked_calls <- 0L
  previous_bridge <- base::getOption("rho.next.bridge"); base::options(rho.next.bridge = bridge)
  request <- base::.subset2(jsonlite::toJSON(list(protocol_version = 1L, request_id = "jsonlite-unloaded", action = "list_objects", payload = list(expected_session = "native", name_contains = "fixture_serializer_absent_", object_type = NULL, directory_ref = NULL, offset = 0L, limit = 20L, scope = list(project = "/isolated", principal = "test", session = "native"))), auto_unbox = TRUE, null = "null"), 1L)
  unavailable <- base::.subset2(jsonlite::toJSON(list(protocol_version = 1L, request_id = "jsonlite-unloaded", outcome = "failed", error = "jsonlite unavailable", value = list(query_error = list(code = "unavailable", message = "jsonlite unavailable")), conditions = list(), conditions_truncated = FALSE), auto_unbox = TRUE, null = "null"), 1L)
  result_path <- base::tempfile("rho-readonly-provider-")
  names <- c("get", "getOption", "local", "loadNamespace", "requireNamespace")
  stopifnot(!any(vapply(names, function(name) base::exists(name, .GlobalEnv, inherits = FALSE), TRUE)))
  on.exit({ base::rm(list = names, envir = .GlobalEnv); base::setHook(event, previous, action = "replace"); base::loadNamespace("jsonlite"); base::options(rho.next.bridge = previous_bridge); base::unlink(result_path) }, add = TRUE)
  for (name in names) base::assign(name, function(...) { masked_calls <<- masked_calls + 1L; stop("Global function mask was called") }, envir = .GlobalEnv)
  base::getOption("rho.next.bridge")$rho_query_json(request, result_path, unavailable)
  stopifnot(file.exists(result_path), masked_calls == 0L)
  base::setHook(event, function(...) { loads <<- loads + 1L }, action = "append")
  base::unloadNamespace("jsonlite")
  before <- base::sort(base::loadedNamespaces())
  base::getOption("rho.next.bridge")$rho_query_json(request, result_path, unavailable)
  stopifnot(identical(base::readLines(result_path, warn = FALSE), unavailable), loads == 0L, masked_calls == 0L, is.null(base::.Internal(getRegisteredNamespace("jsonlite"))), identical(before, base::sort(base::loadedNamespaces())))
  absent <- tryCatch(bridge$rho_readonly_binding("jsonlite", "toJSON"), error = identity)
  stopifnot(inherits(absent, "rho_query_error"), absent$code == "unavailable", loads == 0L)
})
cat("R unloaded object/serializer provider checks passed\n")

local({
  suppressPackageStartupMessages({ library(Matrix); library(SingleCellExperiment) })
  scope <- list(project = '/viewer-test', principal = 'test', session = 'test-session')
  bridge$rho_invalidate_objects()
  observe <- function(name) bridge$rho_observe_object(list(name = name, path = list(), scope = scope))
  read <- function(ref, kind = 'table', ...) {
    args <- list(object_ref=ref, kind=kind, path=list(), start=1L, limit=100L, column_start=1L, column_limit=20L, text_start=1L, text_limit_bytes=16384L, scope=scope)
    args[names(list(...))] <- list(...); bridge$rho_read_object(args)
  }
  assign('viewer_qc', data.frame(id=1:501, group=factor(rep(c('Control','Treated','Recovery'),167)), text=rep('值',501)), .GlobalEnv)
  obs <- observe('viewer_qc'); sorted <- read(obs$object_ref, sort_column=1L, sort_descending=TRUE)
  stopifnot(sorted$total_rows == 501, sorted$row_indices[[1]] == 501, sorted$columns[[1]]$values[[1]]$number == 501)
  filtered <- read(obs$object_ref, filter_column=2L, filter_text='Treated', sort_column=1L, sort_descending=TRUE)
  stopifnot(filtered$total_rows == 167, filtered$row_indices[[1]] == 500)
  assign('viewer_cube', array(1:24,c(2,3,4)), .GlobalEnv)
  cube <- observe('viewer_cube'); slice <- read(cube$object_ref, slice=list(3L))
  stopifnot(slice$columns[[1]]$values[[1]]$number == 13, identical(slice$slice,list(3L)))
  failed <- tryCatch(read(cube$object_ref,slice=list(5L)), error=identity); stopifnot(inherits(failed,'error'))
  assign('viewer_labels', c('处理组 α\n第二行','',NA_character_), .GlobalEnv)
  labels <- observe('viewer_labels')$metadata
  stopifnot(labels$preview[[1]]$text_characters == 9, labels$preview[[2]]$text_characters == 0, labels$preview[[3]]$kind == 'missing')
  assign('viewer_f', function(x) stop('FUNCTION MUST NOT EXECUTE'), .GlobalEnv)
  f <- observe('viewer_f'); stopifnot(grepl('FUNCTION MUST NOT EXECUTE',read(f$object_ref,'text')$values[[1]]$text,fixed=TRUE))
  counts <- as(Matrix(matrix(c(0,1,2,0,0,3),3),sparse=TRUE),'dgCMatrix')
  sx <- SingleCellExperiment(assays=list(counts=counts),colData=DataFrame(group=c('A','B')))
  reducedDim(sx, 'PCA') <- matrix(1:4,2,2)
  assign('viewer_sce',sx,.GlobalEnv)
  sce <- observe('viewer_sce'); stopifnot(identical(unlist(sce$metadata$dimensions),c(3L,2L)))
  assay <- read(sce$object_ref,path=list(list(kind='index',index=1L),list(kind='index',index=1L)))
  stopifnot(assay$columns[[1]]$values[[1]]$number == 0, assay$columns[[2]]$values[[3]]$number == 3)
  cd <- read(sce$object_ref,path=list(list(kind='index',index=3L)))
  stopifnot(cd$total_rows == 2, cd$columns[[1]]$values[[2]]$text == 'B')
  rd <- read(sce$object_ref,path=list(list(kind='index',index=4L),list(kind='index',index=1L)))
  stopifnot(rd$columns[[2]]$values[[2]]$number == 4)
  color <- bridge$rho_object_scalar('green'); stopifnot(color$color == '#00FF00FF')
  assign('viewer_hostile',structure(list(a=1),class='hostile'),.GlobalEnv)
  x <- observe('viewer_hostile'); stopifnot(length(read(x$object_ref,'structure')$children)==0)
  rm(list=ls(.GlobalEnv,pattern='^viewer_'),envir=.GlobalEnv)
  cat('R viewer summaries, full-table order/filter, array slices, source and SCE sparse reads passed\n')
})
