args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) args[[1L]] else getwd()
bridge <- new.env(parent = asNamespace("utils")); bridge$can_inspect_bindings <- requireNamespace("rlang", quietly = TRUE)
stopifnot(bridge$can_inspect_bindings, requireNamespace("jsonlite", quietly = TRUE))
for (file in c("query.R", "objects.R", "dispatch.R")) sys.source(file.path(root, "r/bridge", file), bridge)
local({
  modifyList <- function(x, y, keep.null = TRUE) { x[names(y)] <- y; x }
  scope <- list(project = "/isolated", principal = "test", session = "test-session")
  list_args <- function(...) modifyList(list(expected_session = "test-session", name_contains = "fixture_", object_type = NULL, directory_ref = NULL, offset = 0L, limit = 200L, scope = scope), list(...), keep.null = TRUE)
  observe <- function(name, path = list()) bridge$rho_observe_object(list(name = name, path = path, scope = scope))
  read <- function(ref, kind = "values", ...) bridge$rho_read_object(modifyList(list(object_ref = ref, kind = kind, path = list(), start = 1L, limit = 200L, column_start = 1L, column_limit = 50L, text_start = 1L, text_limit_bytes = 65536L, scope = scope), list(...), keep.null = TRUE))
  fails <- function(code, label) { error <- tryCatch({ force(code); NULL }, error = identity); stopifnot(inherits(error, "error"), grepl(label, conditionMessage(error), fixed = TRUE)) }
  for (i in seq_len(10001)) assign(sprintf("fixture_%05d", i), i, .GlobalEnv)
  page <- bridge$rho_list_objects(list_args()); names <- vapply(page$entries, `[[`, "", "name"); id <- page$directory_ref
  while (!is.null(page$next_offset)) { page <- bridge$rho_list_objects(list_args(directory_ref = id, offset = page$next_offset)); names <- c(names, vapply(page$entries, `[[`, "", "name")) }
  stopifnot(length(names) == 10001L, !anyDuplicated(names), page$complete)
  fails(bridge$rho_list_objects(list_args(directory_ref = id, name_contains = "changed")), "observation_invalid")
  assign("fixture_00001", "changed", .GlobalEnv)
  fails(bridge$rho_list_objects(list_args(directory_ref = id)), "content_changed")
  rm(list = ls(.GlobalEnv, pattern = "^fixture_"), envir = .GlobalEnv)
  bridge$rho_invalidate_objects()
  assign("fixture_table", data.frame(a = 1:501, b = seq_len(501), text = rep(paste(rep("界", 1000), collapse = ""), 501)), .GlobalEnv)
  object <- observe("fixture_table"); page <- read(object$object_ref, "table", start = 401, column_start = 2)
  stopifnot(page$columns[[1L]]$values[[1L]]$number == 401, page$next_start > 401, page$columns[[2L]]$values[[1L]]$next_text_start > 1)
  text <- read(object$object_ref, "text", path = list(list(kind = "index", index = 3L)), start = 401, text_start = 101)
  stopifnot(nchar(text$values[[1L]]$text) == 900)
  assign("fixture_list", list(a = list(1:500, rep("long", 300)), repeated = 1, repeated = 2), .GlobalEnv)
  object <- observe("fixture_list")
  fails(read(object$object_ref, path = list(list(kind = "name", name = "repeated"))), "invalid_path")
  page <- read(object$object_ref, path = list(list(kind = "index", index = 1L), list(kind = "index", index = 1L)), start = 301)
  stopifnot(length(page$values) == 200, page$values[[1L]]$number == 301)
  assign("fixture_matrix", matrix(seq_len(12000), nrow = 300L, ncol = 40L), .GlobalEnv)
  matrix_object <- observe("fixture_matrix")
  matrix_page <- read(matrix_object$object_ref, "table", start = 251L, column_start = 30L)
  stopifnot(length(matrix_page$columns) == 11L, matrix_page$columns[[1L]]$values[[1L]]$number == 8951,
            sum(vapply(matrix_page$columns, function(x) length(x$values), 1L)) <= 2000L)
  assign("fixture_named", setNames("value", paste(rep("名", 1000), collapse = "")), .GlobalEnv)
  named_object <- observe("fixture_named")
  named_page <- read(named_object$object_ref, "names")
  stopifnot(named_page$values[[1L]]$next_text_start > 1)
  named_text <- read(named_object$object_ref, "text", text_attribute = "names", text_start = named_page$values[[1L]]$next_text_start)
  stopifnot(!is.null(named_text$values[[1L]]$text))
  fails(read(named_object$object_ref, "text", text_attribute = "names", text_limit_bytes = 1L), "budget_exhausted")
  assign("fixture_units", as.difftime(1:3, units = "hours"), .GlobalEnv)
  stopifnot(observe("fixture_units")$metadata$attributes[[1L]]$values[[1L]] == "hours")
  assign("fixture_special", c(NA_real_, NaN, Inf, -Inf, 4), .GlobalEnv)
  page <- read(observe("fixture_special")$object_ref)
  stopifnot(identical(vapply(page$values, `[[`, "", "kind"), c("missing", "non_finite", "non_finite", "non_finite", "value")))
  assign("fixture_factor", factor(c("a", "b", NA)), .GlobalEnv)
  page <- read(observe("fixture_factor")$object_ref, "levels")
  stopifnot(page$values[[2L]]$text == "b")
  assign("fixture_date", as.Date("2020-01-01") + 0:1000, .GlobalEnv)
  assign("length.Date", function(...) stop("USER LENGTH CALLED"), .GlobalEnv)
  page <- read(observe("fixture_date")$object_ref, start = 500)
  stopifnot(length(page$values) == 200)
  delayedAssign("fixture_promise", stop("PROMISE FORCED"), assign.env = .GlobalEnv)
  makeActiveBinding("fixture_active", function(...) stop("ACTIVE BINDING CALLED"), .GlobalEnv)
  assign("fixture_custom", structure(1:5, class = "hostile"), .GlobalEnv)
  assign("print.hostile", function(...) stop("USER METHOD CALLED"), .GlobalEnv)
  stopifnot(observe("fixture_promise")$metadata$kind == "promise", observe("fixture_active")$metadata$kind == "active_binding", identical(observe("fixture_custom")$metadata$supported_reads, list("structure")))
  for (name in c("fixture_promise", "fixture_active", "fixture_custom")) {
    safe <- observe(name)
    structure <- read(safe$object_ref, "structure")
    stopifnot(structure$root_name == name, identical(structure$observed_path, list()), structure$metadata$kind == safe$metadata$kind)
    fails(read(safe$object_ref, "values"), "unsupported")
  }
  nested_path <- list(list(kind = "index", index = 1L), list(kind = "index", index = 1L))
  nested <- observe("fixture_list", nested_path)
  nested_page <- read(nested$object_ref, "values", start = 301L)
  stopifnot(nested_page$root_name == "fixture_list", identical(nested_page$observed_path, nested_path), nested_page$values[[1L]]$number == 301L)
  object <- observe("fixture_date")
  fails(read(object$object_ref, scope = modifyList(scope, list(principal = "other"))), "observation_invalid")
  bridge$rho_object_state$handles[[object$object_ref]]$used <- bridge$rho_object_now() - 60001
  fails(read(object$object_ref), "observation_expired")
  object <- observe("fixture_date")
  bridge$rho_object_state$handles[[object$object_ref]]$created <- bridge$rho_object_now() - 300001
  fails(read(object$object_ref), "observation_expired")
  object <- observe("fixture_date")
  result <- bridge$rho_dispatch(list(protocol_version = 1L, request_id = "failed", action = "execute", payload = list(code = "stop('intended failure')")))
  stopifnot(result$outcome == "failed")
  fails(read(object$object_ref), "observation_expired")
  bridge$rho_invalidate_objects()
  for (i in 1:32) observe("fixture_date")
  fails(observe("fixture_date"), "budget_exhausted")
  rm(list = ls(.GlobalEnv, pattern = "^fixture_|^length.Date$|^print.hostile$"), envir = .GlobalEnv)
})
cat("R object progressive inspection checks passed\n")
