[package]
name = "rho-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rho-process-engine = { path = "../../process-engine" }
rho-process-owner = { path = "../../../plugins/process/backend/owner" }
async-trait.workspace = true
rho-contract = { path = "../../contract" }
rho-operation = { path = "../../operation" }
rho-execution = { path = "../../execution" }
tokio.workspace = true
serde_json.workspace = true
