ensure_demo_directories <- function() {
  dirs <- c("data/processed", "output/figures")
  for (directory in dirs) dir.create(directory, recursive = TRUE, showWarnings = FALSE)
}

save_demo_plot <- function(path, plot_fn, width = 900, height = 620) {
  ensure_demo_directories()
  png(path, width = width, height = height, res = 120)
  on.exit(dev.off(), add = TRUE)
  plot_fn()
}

write_demo_report <- function(path, summary, model) {
  ensure_demo_directories()
  coefficients <- coef(model)
  rows <- paste(
    sprintf(
      "<tr><td>%s</td><td>%.2f</td><td>%s</td></tr>",
      names(summary$life_expectancy),
      summary$life_expectancy,
      format(round(summary$population), big.mark = ",", scientific = FALSE)
    ),
    collapse = "\n"
  )
  coefficient_rows <- paste(
    sprintf(
      "<tr><td>%s</td><td>%.4f</td></tr>", names(coefficients), coefficients),
    collapse = "\n"
  )
  html <- c(
    "<!doctype html>",
    "<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Rho demo report</title>",
    "<style>body{font:16px/1.5 system-ui,sans-serif;max-width:900px;margin:40px auto;padding:0 24px;color:#202936}h1{color:#214ea8}table{border-collapse:collapse;width:100%;margin:16px 0}th,td{border:1px solid #dde3ec;padding:8px;text-align:left}th{background:#edf3ff}.note{background:#f8fafc;border-left:4px solid #2863d6;padding:12px}</style>",
    "</head><body>",
    "<h1>Countries at a glance</h1>",
    "<p>This report was generated by a reproducible R script inside Rho. It uses the latest available year in the Gapminder data and a simple linear model.</p>",
    "<div class=\"note\"><strong>What to inspect in Rho:</strong> the source script in Editor, objects in Objects, plots in Plots, and this HTML document in Viewer.</div>",
    "<h2>Average values by continent</h2>",
    "<table><thead><tr><th>Continent</th><th>Life expectancy</th><th>Population</th></tr></thead><tbody>",
    rows,
    "</tbody></table>",
    "<h2>Model coefficients</h2>",
    "<p><code>lifeExp ~ log10(gdpPercap) + continent</code></p>",
    "<table><thead><tr><th>Term</th><th>Estimate</th></tr></thead><tbody>",
    coefficient_rows,
    "</tbody></table>",
    "<p><small>Data: Gapminder data excerpt by Jennifer Bryan. See <code>data/raw/source.json</code> for provenance.</small></p>",
    "</body></html>"
  )
  writeLines(html, path, useBytes = TRUE)
  invisible(path)
}
