// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessReconcileRecovery = { source_operation_id: string, action?: string | null, };
