// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeProcessIdentity } from "./NativeProcessIdentity.js";
import type { ProcessObservationCompleteness } from "./ProcessObservationCompleteness.js";

export type ProcessReconciliation = { source_operation_id: string, observed: Array<NativeProcessIdentity>, signalled: Array<NativeProcessIdentity>, remaining: Array<NativeProcessIdentity>, no_matching_processes_observed: boolean, completeness: ProcessObservationCompleteness, notices: Array<string>, };
