// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessActivity } from "./ProcessActivity.js";

export type ProcessStatus = {
/**
 * Native scheduling only. Committed outcomes belong to operation.get.
 */
activities: Array<ProcessActivity>, capacity: number, };
