// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { ProcessTermination } from "./ProcessTermination.js";
import type { ResourceReference } from "./ResourceReference.js";

export type ProcessRunResult = { operation: OperationId,
/**
 * Exact JSON-encoded ProcessReport, including bounded original byte streams.
 */
report: ResourceReference, pid: number | null, termination: ProcessTermination, exit_code: number | null, exit_signal: number | null, };
