// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completeness of visible native process evidence, distinct from transport status.
 */
export type ProcessObservationCompleteness = "complete" | "partial" | "unknown";
