// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { OperationId } from "./OperationId.js";
import type { OutputCapture } from "./OutputCapture.js";
import type { ProcessTermination } from "./ProcessTermination.js";
import type { ResourceReference } from "./ResourceReference.js";

export type ProcessRunRecovery = { operation: OperationId, project_root: string, pid: number | null,
/**
 * Native report transfer may fail after execution. An empty reference never
 * establishes absence of effects or authorizes another execution.
 */
report: ResourceReference | null, native_termination: ProcessTermination | null, report_digest: ContentDigest | null, stdout: OutputCapture | null, stderr: OutputCapture | null, report_transfer_confirmed: boolean, automatic_reexecution: boolean, };
