// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunLocalArguments = { program: string, args: Array<string>, stdin: string | null, timeout_ms: number, output_limit_bytes: number, };
