// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RemoteExecutionOutcome } from "./RemoteExecutionOutcome.js";
import type { RemoteTarget } from "./RemoteTarget.js";
import type { ResourceReference } from "./ResourceReference.js";

export type RemoteRunResult = { operation: OperationId, target: RemoteTarget,
/**
 * Original JSON RemoteExecutionReport, including bounded transport streams.
 */
report: ResourceReference, remote_exit_code: number | null, native_outcome: RemoteExecutionOutcome, };
