// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessActivity } from "./ProcessActivity.js";
import type { RemoteTarget } from "./RemoteTarget.js";

export type RemoteStatus = { target: RemoteTarget | null, target_key: string | null, activities: Array<ProcessActivity>, capacity: number, };
