// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteTarget } from "./RemoteTarget.js";

export type RemoteProcessRecovery = { source_operation_id: string, target: RemoteTarget, action: string, automatic_reexecution: boolean, };
