// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteTarget } from "./RemoteTarget.js";

export type RemoteConfiguration = {
/**
 * No connection or operation is possible until an explicit target is set.
 */
target: RemoteTarget | null, };
