// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessReport } from "./ProcessReport.js";
import type { RemoteExecutionOutcome } from "./RemoteExecutionOutcome.js";
import type { RemoteTarget } from "./RemoteTarget.js";

export type RemoteExecutionReport = { target: RemoteTarget, transport: ProcessReport, remote_exit_code: number | null, outcome: RemoteExecutionOutcome, notice: string, };
