// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteTarget = { host_alias: string, project_root: string, slurm_cluster: string | null, };
