// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDigest } from "./ContentDigest.js";
import type { OperationId } from "./OperationId.js";
import type { OutputCapture } from "./OutputCapture.js";
import type { RemoteExecutionOutcome } from "./RemoteExecutionOutcome.js";
import type { RemoteTarget } from "./RemoteTarget.js";
import type { ResourceReference } from "./ResourceReference.js";

export type RemoteRunRecovery = { operation: OperationId, project_root: string, target: RemoteTarget, report: ResourceReference | null, report_digest: ContentDigest | null, native_outcome: RemoteExecutionOutcome, stdout: OutputCapture, stderr: OutputCapture, report_transfer_confirmed: boolean, automatic_reexecution: boolean, action: string, };
