// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlurmJobRef } from "./SlurmJobRef.js";
import type { SlurmLookup } from "./SlurmLookup.js";

export type SlurmCancelRecovery = { source_operation_id: string, automatic_reexecution: boolean, } | { source_operation_id: string, lookup: SlurmLookup, } | { source_operation_id: string, job: SlurmJobRef, };
