// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { SlurmLookup } from "./SlurmLookup.js";
import type { SlurmSnapshotStatus } from "./SlurmSnapshotStatus.js";

export type SlurmSnapshot = { source_operation: OperationId, status: SlurmSnapshotStatus, lookup: SlurmLookup | null, notice: string, };
