// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlurmObservation } from "./SlurmObservation.js";

export type SlurmLookup = { source_operation_id: string, jobs: Array<SlurmObservation>, accounting_lookback_days: number, };
