// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlurmJobRef } from "./SlurmJobRef.js";

export type SlurmObservation = { job: SlurmJobRef, state: string, exit_code: string | null, source: string, };
