// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlurmObservation } from "./SlurmObservation.js";

export type SlurmCancellation = { request_sent: boolean, before: SlurmObservation, after: SlurmObservation | null, notice: string, };
