[package]
name = "rho-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rho"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
rho-store = { path = "../rho-store" }
serde_json.workspace = true
