[package]
name = "rho-next-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
rho-next-contract = { path = "../contract" }
rho-next-operation = { path = "../operation" }
rho-next-sqlite = { path = "../adapters/sqlite" }
rho-next-r-runtime = { path = "../adapters/r-runtime" }
rho-next-project = { path = "../project" }
rho-next-git = { path = "../adapters/git" }
rho-next-workspace = { path = "../workspace" }
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true
