/** One retained-package milestone: source entries, Files quotes and live Viewer pixels. */
import {test,expect,type Page,type FrameLocator} from '@playwright/test';
import {spawn,execFileSync} from 'node:child_process';
import {mkdtemp,mkdir,rm,realpath,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {verifyAgentBuild} from '../../scripts/agent-plugin-artifact.mjs';
import {verifyRBuild} from '../../scripts/r-plugin-artifact.mjs';

const binary=resolve('../target/debug/rho'),windowId='annotation-foundation',key=(id:string)=>({id,version:1});
let directory:string,project:string,url:URL,host:ReturnType<typeof spawn>,instances:Record<string,any>={},session:string,run:any,copy:any,core:string,completed=false;
const filesTask='foundation-files',viewerTask='foundation-viewer';
const stage=process.env.RHO_ANNOTATION_FOUNDATION_STAGE??'all';
if(!['all','viewer','files'].includes(stage))throw Error('Unknown annotation acceptance stage.');
const entryFilter=(process.env.RHO_ANNOTATION_FOUNDATION_ENTRIES??'').split(',').filter(Boolean),allEntries=['editor','help','objects','packages','plots','console','viewer','agent'];
if(entryFilter.some(name=>!allEntries.includes(name)))throw Error('Unknown annotation source entry.');
const names=stage==='viewer'?['r','annotations','agent','viewer']:stage==='files'?['annotations','agent','files']:entryFilter.length?[...new Set(['r','annotations','agent',...entryFilter,...(entryFilter.includes('editor')?['files']:[]),...(entryFilter.includes('packages')?['help']:[])])]:['r','annotations','agent','files','editor','help','objects','packages','plots','console','viewer'];
if(names.includes('r')&&(!process.env.RHO_ARK||!process.env.RHO_R_HOME))throw Error('Set RHO_ARK and RHO_R_HOME before the R annotation stage.');
const html='<html><head><style>body{font:18px system-ui;padding:24px}#result{background:#2863d6;color:white;padding:40px}input,button{font:inherit;margin:12px 0}</style></head><body><h1>Interactive Viewer</h1><input aria-label="Viewer label" value="Original"><button onclick="document.querySelector(\'#result\').style.background=\'#15803d\';document.querySelector(\'#result\').textContent=\'Filtered result: 2 rows\'">Filter</button><div id="result">Original result: 3 rows</div></body></html>';
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
async function port(method:string,params:any){const reply=await fetch(new URL('/api/host',url),{method:'POST',headers:{Authorization:`Bearer ${url.hash.slice(7)}`,'Content-Type':'application/json','X-Rho-Studio-Window':windowId},body:JSON.stringify({project_root:project,frame:{id:crypto.randomUUID(),request:{method,params}}})}).then(r=>r.json());if(!reply.ok)throw Error(reply.error);return reply.result;}
async function query(id:string,arguments_:any){const result=await port('query_snapshot',{capability:key(id),arguments:arguments_});expect(result.status,JSON.stringify(result)).toBe('ready');return result.data;}
async function invoke(id:string,arguments_:any){let record=await port('invoke',{capability:key(id),arguments:arguments_,client_request_id:crypto.randomUUID(),preconditions:[]});for(let i=0;i<100&&!['succeeded','failed','uncertain','cancelled'].includes(record.status);i++){await new Promise(done=>setTimeout(done,40));record=await port('get_operation',{operation_id:record.operation.operation_id});}expect(record.status,JSON.stringify(record.error)).toBe('succeeded');return record.output;}
async function binding(name:string,id:string){return query('plugins.resolve',{instance:instances[name],capability:key(id)});}
async function read(name:string,id:string,args:any){return query(id,{binding:await binding(name,id),arguments:args,preconditions:null});}
async function write(name:string,id:string,args:any){return invoke(id,{binding:await binding(name,id),arguments:args,preconditions:null});}
async function native(id:string,args:any){return (await read('r',id,{expected_session:session,...args})).data;}
async function open(name:string,configuration:any,contribution=name){const layout=await query('windows.layout',{window:windowId});return (await invoke('windows.open_view',{expected_layout_version:layout.version,group:layout.layout.kind==='tabs'?layout.layout.id:null,view:{instance:instances[name],window:windowId,contribution,configuration,state:{}}})).view;}
async function show(page:Page){const address=new URL(url);address.searchParams.set('window',windowId);await page.goto(address.href);}
const frame=(page:Page,view:any)=>page.locator(`[data-plugin-frame="${view.view}"]`).frameLocator('iframe');
async function openedNotes(source:any){const saved=await query('views.inspect',{view:source.view});return saved.state.agent?.annotation?.opened??saved.state.annotation?.opened;}
async function select(page:Page,view:any){const layout=await query('windows.layout',{window:windowId});const choose=(node:any):any=>node.kind==='tabs'&&node.views.includes(view.view)?{...node,selected:view.view}:node.kind==='split'?{...node,children:node.children.map(choose)}:node;await invoke('windows.update_layout',{window:windowId,expected_version:layout.version,layout:choose(layout.layout)});await page.reload();}
async function addToDraft(page:Page,notes:FrameLocator,view:any,task:string){
 const check=notes.getByRole('checkbox',{name:'Select visible notes'});await check.check();await expect(check).toBeChecked();await notes.getByRole('button',{name:'Add to Agent',exact:true}).click();await notes.getByLabel('Agent instance',{exact:true}).selectOption(instances.agent.instance);await notes.getByRole('button',{name:'Open Agent',exact:true}).click();
 await expect.poll(async()=>!!(await query('views.inspect',{view:view.view})).state.agentOpened).toBe(true);const opened=(await query('views.inspect',{view:view.view})).state.agentOpened;
 const agent=frame(page,opened);await expect(agent.getByLabel('Select task',{exact:true}).locator(`option[value=\"rho:${task}\"]`)).toHaveCount(1);await agent.getByLabel('Select task',{exact:true}).selectOption(`rho:${task}`);await expect(agent.getByLabel('Agent message',{exact:true})).toHaveValue('Existing draft 中文');await agent.getByRole('button',{name:'Take over',exact:true}).click();await expect(agent.getByLabel('Agent message',{exact:true})).toBeEditable();await agent.locator('#component-request').evaluate(element=>{(element as HTMLDetailsElement).open=true;});await agent.getByRole('button',{name:'Add context to draft',exact:true}).click();
 return opened;
}
async function screenshots(page:Page,notes:FrameLocator,info:any,label:string){for(const width of [600,320]){await page.setViewportSize({width,height:900});await notes.locator('#annotation-editor').scrollIntoViewIfNeeded();expect(await notes.locator('body').evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:info.outputPath(`${label}-${width}.png`)});}await page.setViewportSize({width:1440,height:900});}

test.beforeAll(async()=>{
 test.setTimeout(stage==='all'?240000:120000);const started=Date.now();
 const packages=JSON.parse(await readFile(resolve(process.env.RHO_ANNOTATION_FOUNDATION_PACKAGES??'../target/plugin-refactor/annotation-foundation-build.json'),'utf8'));
 verifyAgentBuild(packages.agent,resolve('..'));verifyRBuild(packages.r,resolve('..'));
 directory=await mkdtemp(join(tmpdir(),'rho-annotation-foundation-run-'));project=join(directory,'project');await mkdir(project);project=await realpath(project);const database=join(directory,'state.sqlite');core=hash(await readFile(binary));await writeFile(join(project,'analysis.R'),'x <- 1\nprint(42)\n');execFileSync('git',['init','-q',project]);
 const snapshots:Record<string,any>={};for(const name of names)snapshots[name]=JSON.parse(execFileSync(binary,['--database',database,'plugins','snapshot',packages[name],'--target',['r','annotations','agent','files','editor'].includes(name)?'aarch64-apple-darwin':'ui-web'],{encoding:'utf8'})).result;const snapshotsSeconds=(Date.now()-started)/1000;console.log(JSON.stringify({stage,snapshots_seconds:snapshotsSeconds}));
 host=spawn(binary,['--database',database,'--project',project,'workbench'],{stdio:['ignore','pipe','pipe']});url=new URL(await new Promise<string>((done,reject)=>{let output='',errors='';const timer=setTimeout(()=>reject(Error(`Disposable Host startup timed out: ${errors}`)),30000);host.stderr!.on('data',b=>errors+=b);host.stdout!.on('data',b=>{output+=b;const found=output.match(/http:\/\/127\.0\.0\.1:\d+\/\?plugin-window#token=[a-z0-9]+/);if(found){clearTimeout(timer);done(found[0]);}});host.once('exit',code=>{clearTimeout(timer);reject(Error(`Host exited ${code}: ${errors}`));});}));
 const hostStarted=Date.now();
 const manifests=Object.fromEntries(await Promise.all(Object.entries(snapshots).map(async([name,snapshot])=>[name,(await query('plugins.inspect',{revision:snapshot.revision})).manifest])));
 const available=new Set(Object.values(manifests).flatMap((manifest:any)=>manifest.capabilities.map((entry:any)=>entry.capability.id)));
 const hostReads=new Set(['plugins.instances','plugins.resolve','plugins.inspect','windows.layout','windows.update_layout','windows.open_view','workspace.paths','operation.get','operation.list_recent','resources.read']);
 for(const [name,snapshot] of Object.entries(snapshots).sort((a,b)=>a[0]==='agent'?-1:b[0]==='agent'?1:0)){const activationStarted=Date.now(),manifest=manifests[name];instances[name]=(await invoke('plugins.activate',{revision:snapshot.revision,artifact:snapshot.artifacts[0],target:['r','annotations','agent','files','editor'].includes(name)?'aarch64-apple-darwin':'ui-web',alias:name,configuration:name==='r'?{ark:await realpath(process.env.RHO_ARK!),r_home:await realpath(process.env.RHO_R_HOME!),execution_timeout_seconds:30}:{},optional_capabilities:(manifest.optional_requires??[]).filter((entry:any)=>available.has(entry.capability.id)||hostReads.has(entry.capability.id)).map((entry:any)=>entry.capability)})).instance.identity;console.log(JSON.stringify({activated:name,seconds:(Date.now()-activationStarted)/1000}));}
 if(instances.r){session=(await write('r','r.create_session',{})).session_id;
 run=await write('r','r.execute',{expected_session:session,code:`annotation_object <- seq_len(3); writeLines(${JSON.stringify(html)}, 'annotation-viewer.html'); getOption('viewer')('annotation-viewer.html'); plot(1:3, main='Annotation source'); cat('Original Console annotation output\\n'); 1L`});
 const grouped=await native('r.packages',{filter:'parallel',grouped:true}),copies=await native('r.packages',{observation_id:grouped.observation_id,package_name:'parallel'});const installed=copies.packages[0];copy={nativeSession:session,observation:grouped.observation_id,package:'parallel',libraryPath:installed.library_path,version:installed.version};}
 const activationSeconds=(Date.now()-hostStarted)/1000;for(const task of [filesTask,viewerTask]){const conversation=await write('agent','agent.model.create',{conversation_id:task,profile:'project'});await write('agent','agent.model.draft',{conversation_id:task,draft_version:conversation.draft_version,content:{text:'Existing draft 中文',context:[],assets:[]},grant:null});}
 console.log(JSON.stringify({stage,snapshots_seconds:snapshotsSeconds,host_activation_seconds:activationSeconds,owner_setup_seconds:(Date.now()-hostStarted)/1000-activationSeconds,total_setup_seconds:(Date.now()-started)/1000}));
});
test.afterAll(async()=>{if(host?.exitCode===null){host.kill('SIGINT');await new Promise<void>(done=>host.once('exit',()=>done()));}if(directory&&completed)await rm(directory,{recursive:true,force:true});else if(directory)console.error(`Incomplete annotation milestone retained: ${directory}`);});

test('captures the interactive Viewer, keeps marks and original pixels through draft and refresh',async({page},info)=>{
 test.setTimeout(90000);completed=false;const sourceView=await open('viewer',{source:instances.r}),source=frame(page,sourceView);await show(page);const widget=source.frameLocator('#surface iframe');await widget.getByLabel('Viewer label').fill('Current filtered view 中文');await widget.getByRole('button',{name:'Filter',exact:true}).click();await expect(widget.locator('#result')).toHaveText('Filtered result: 2 rows');await page.screenshot({path:info.outputPath('viewer-current.png')});await source.getByRole('button',{name:'Annotate',exact:true}).click();await source.getByRole('dialog',{name:'Annotate this input'}).getByRole('button',{name:'Capture current view',exact:true}).click();await expect.poll(async()=>!!await openedNotes(sourceView)).toBe(true);
 const view=await openedNotes(sourceView),notes=frame(page,view);await expect(notes.locator('#capture-image')).toBeVisible();await expect(notes.locator('#evidence-status')).toContainText('Frozen evidence');const initial=(await query('views.inspect',{view:view.view})).state;expect(initial.capture.original_media).toBe(false);await notes.locator('#capture-image').screenshot({path:info.outputPath('viewer-captured.png')});
 await notes.getByRole('button',{name:'Rectangle',exact:true}).click();const bounds=(await notes.locator('#mark-canvas').boundingBox())!;await page.mouse.move(bounds.x+bounds.width*.1,bounds.y+bounds.height*.15);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.5,bounds.y+bounds.height*.3);await page.keyboard.press('Escape');await page.mouse.up();await expect(notes.locator('#mark-list')).not.toContainText('rectangle');await page.mouse.move(bounds.x+bounds.width*.1,bounds.y+bounds.height*.15);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.5,bounds.y+bounds.height*.3);await page.mouse.up();await expect(notes.locator('#mark-list')).toContainText('1. rectangle');await notes.getByLabel('Note',{exact:true}).fill('Review filtered Viewer capture');await page.keyboard.press('Control+Enter');await expect(notes.locator('#editor-title')).toContainText('revision 1');const saved=(await query('views.inspect',{view:view.view})).state.selected;
 await screenshots(page,notes,info,'viewer');await addToDraft(page,notes,view,viewerTask);await expect.poll(async()=>(await read('agent','agent.model.conversation',{conversation_id:viewerTask})).draft_content.context.length).toBe(1);const draft=(await read('agent','agent.model.conversation',{conversation_id:viewerTask})).draft_content;expect(draft.text).toBe('Existing draft 中文');expect(draft.context.map((item:any)=>item.reference.selector)).toContainEqual(saved);await page.reload();expect((await read('agent','agent.model.conversation',{conversation_id:viewerTask})).draft_content).toEqual(draft);await select(page,view);await expect(notes.locator('#mark-list')).toContainText('1. rectangle');expect((await query('views.inspect',{view:view.view})).state.capture).toEqual(initial.capture);
 await write('r','r.execute',{expected_session:session,code:`writeLines('<h1>New output</h1>', 'next-viewer.html'); getOption('viewer')('next-viewer.html'); 2L`});await notes.getByRole('button',{name:'Check original source',exact:true}).click();const retained=await read('annotations','annotations.read',{kind:'read',annotation:saved});expect(retained.evidence.anchor.capture).toEqual(initial.capture);expect(retained.revision.marks).toHaveLength(1);await expect(notes.locator('#capture-image')).toBeVisible();expect(hash(await readFile(binary))).toBe(core);
 await writeFile(info.outputPath('result.json'),JSON.stringify({viewer_note:saved,capture:initial.capture,marks:retained.revision.marks,draft,core_sha256:core,original_output_retained:true,new_output_cannot_replace_capture:true,sent:false,limits:'Captured live viewport; no original-image/data-ID/zoom provenance claim. No model Send or OS IME.'},null,2)+'\n');completed=true;
});
test('closes Files selected text, keyboard, draft and source change',async({page},info)=>{
 test.setTimeout(120000);completed=false; const sourceView=await open('files',{editor:null,editor_group:null,runtime:null});await show(page);const source=frame(page,sourceView);await source.getByRole('button',{name:/analysis\.R/}).click();await source.getByRole('button',{name:'Annotate',exact:true}).click();const dialog=source.getByRole('dialog',{name:'Annotate this input'});await expect(dialog.locator('[data-annotation=preview]')).toContainText('x <- 1');
 await dialog.locator('[data-annotation=preview]').evaluate(element=>{const node=element.firstChild!,start=node.textContent!.indexOf('x <- 1'),range=document.createRange();range.setStart(node,start);range.setEnd(node,start+6);const selection=getSelection()!;selection.removeAllRanges();selection.addRange(range);});const nearby=dialog.getByRole('button',{name:'Add note',exact:true});await expect(nearby).toBeVisible();await nearby.focus();await page.keyboard.press('Enter');await expect.poll(async()=>!!await openedNotes(sourceView)).toBe(true);const view=await openedNotes(sourceView),notes=frame(page,view);await expect(notes.locator('#frozen-text')).toHaveText('x <- 1');await notes.getByLabel('Note',{exact:true}).fill('Selected Files quote 中文');await page.keyboard.press('Control+Enter');await expect(notes.locator('#editor-title')).toContainText('revision 1');const saved=(await query('views.inspect',{view:view.view})).state.selected;
 await screenshots(page,notes,info,'files');await notes.locator('#notes .note-copy').first().focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(notes.locator('#editor-title')).toContainText('revision 1');
 await page.setViewportSize({width:320,height:900});const draftView=await addToDraft(page,notes,view,filesTask),draftFrame=frame(page,draftView);expect(await draftFrame.locator('body').evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:info.outputPath('files-agent-320.png')});await page.setViewportSize({width:1440,height:900});await expect.poll(async()=>(await read('agent','agent.model.conversation',{conversation_id:filesTask})).draft_content.context.length).toBe(1);
 await select(page,view);await expect(notes.locator('#frozen-text')).toHaveText('x <- 1');await notes.getByLabel('Note',{exact:true}).fill('Retained unsaved draft');await page.keyboard.press('Escape');await expect(source.getByRole('button',{name:'Annotate',exact:true})).toBeVisible();await source.getByRole('button',{name:'Annotate',exact:true}).hover();await expect(source.getByRole('button',{name:'Annotate',exact:true})).toContainText('· 1');await select(page,view);await expect(notes.getByLabel('Note',{exact:true})).toHaveValue('Retained unsaved draft');
 await writeFile(join(project,'analysis.R'),'x <- 2\nprint(84)\n');await notes.getByRole('button',{name:'Check original source',exact:true}).click();await expect(notes.locator('#evidence-status')).toContainText(/changed/i);expect((await read('annotations','annotations.read',{kind:'read',annotation:saved})).evidence.fragment.text).toBe('x <- 1');
 await writeFile(info.outputPath('result.json'),JSON.stringify({source:'files',files_note:saved,quote:'x <- 1',keyboard:['Enter near selection','Control+Enter save','Up/Down notes','Escape preserves draft'],source_changed:true,core_sha256:core,sent:false},null,2)+'\n');completed=true;
});

test('smokes all eight source entries and the Agent task anchor',async({page},info)=>{
 test.setTimeout(180000);completed=false;const entries:string[]=[],failures:{name:string;error:string}[]=[];
 const file=entryFilter.length&&!entryFilter.includes('editor')?null:(await read('files','files.snapshot',{paths:['analysis.R'],limit:1})).files[0];
 const sources:[string,any,string?][]=[['editor',{source:instances.files,file}],['help',{source:instances.r,copy,topic:'mclapply'}],['objects',{source:instances.r,object_group:null,object:{name:'annotation_object',path:[]}},'object'],['packages',{source:instances.r,help:instances.help,help_group:null}],['plots',{source:instances.r,selection:null,pinned:false,plot_group:null}],['console',{source:instances.r}],['viewer',{source:instances.r}],['agent',{}]];
 for(const [name,configuration,contribution] of sources.filter(([name])=>!entryFilter.length||entryFilter.includes(name))){try{const view=await open(name,configuration,contribution);await show(page);const source=frame(page,view);
  if(name==='packages'){await source.getByLabel('Search Packages').fill('parallel');await source.getByRole('button',{name:/^parallel,/}).click();}
  if(name==='plots'){await expect(source.locator('.plot-original img')).toBeVisible();await source.getByRole('button',{name:'Plot Actions',exact:true}).click();await source.getByRole('menuitem',{name:'Annotate',exact:true}).click();}
  else if(name==='console'){await source.getByRole('button',{name:'Run Details',exact:true}).click();const details=source.locator('#details-content details').first();await details.locator('summary').click();await details.getByRole('button',{name:'Annotate',exact:true}).click();}
  else {if(name==='agent'){await source.getByLabel('Select task',{exact:true}).selectOption(`rho:${filesTask}`);await source.getByRole('button',{name:'Task actions',exact:true}).click();}await source.getByRole('button',{name:'Annotate',exact:true}).click();}
  const dialog=source.getByRole('dialog',{name:'Annotate this input'});if(name==='help')await dialog.getByLabel('Annotation inclusion').selectOption('excerpt');
  const openNotes=dialog.getByRole('button',{name:'Open notes',exact:true}),alert=dialog.locator('[data-annotation=error]');
  for(let retry=0;retry<3;retry++){
   await expect.poll(async()=>await openNotes.isEnabled()||await alert.isVisible()).toBe(true);
   const reason=await alert.textContent()??'';
   if(await openNotes.isEnabled()||!await alert.isVisible()||!/busy|Open a current object observation/i.test(reason))break;
   if(name==='objects')await expect(source.getByRole('button',{name:'Annotate',exact:true})).toBeEnabled();
   await dialog.getByRole('button',{name:'Prepare current source',exact:true}).click();
  }
  await expect(openNotes,await alert.textContent()??'').toBeEnabled();await expect(dialog.locator('[data-annotation=preview]')).not.toBeEmpty();
  if(['help','objects','packages','console','agent'].includes(name))await expect(dialog.getByLabel('Source anchor')).toContainText(name==='agent'?filesTask:name==='objects'?'annotation_object':name==='console'?'Whole item':'parallel');
  if(name==='agent'){await dialog.getByLabel('Source anchor').selectOption('0');await dialog.getByRole('button',{name:'Open notes',exact:true}).click();await expect.poll(async()=>!!await openedNotes(view)).toBe(true);const opened=await openedNotes(view);await expect(frame(page,opened).locator('#evidence-status')).toContainText('Frozen evidence');const state=(await query('views.inspect',{view:opened.view})).state;const evidence=(await read('annotations','annotations.read',{kind:'evidence',evidence_id:state.evidence}));expect(evidence.evidence.anchor.kind).toBe('structured');}
  else await dialog.getByRole('button',{name:'Back to source',exact:true}).click();entries.push(name);
 }catch(error){failures.push({name,error:String(error)});console.error(`Annotation entry ${name}: ${String(error)}`);}
 }
 await writeFile(info.outputPath('result.json'),JSON.stringify({entries,failures,agent_task_anchor:entries.includes('agent'),core_sha256:core},null,2)+'\n');expect(failures).toEqual([]);completed=true;
});
