import {test,expect} from '@playwright/test';
import {spawn,execFileSync} from 'node:child_process';
import {mkdtemp,mkdir,rm,realpath,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {buildCaptureSource} from '../../scripts/fixtures/annotation-captures.mjs';

const binary=resolve('../target/debug/rho'),windowId='annotation-ui-window';
const key=(id:string)=>({id,version:1});
const digest=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
let fileView:any,captureOwner:any,agent:any;let directory:string,project:string,url:URL,host:ReturnType<typeof spawn>,annotation:any,files:any,view:any,completed=false,core:string;
async function port(method:string,params:any){const response=await fetch(new URL('/api/host',url),{method:'POST',headers:{Authorization:`Bearer ${url.hash.slice(7)}`,'Content-Type':'application/json','X-Rho-Studio-Window':windowId},body:JSON.stringify({project_root:project,frame:{id:crypto.randomUUID(),request:{method,params}}})}).then(r=>r.json());if(!response.ok)throw Error(response.error);return response.result;}
async function query(id:string,args:any){const response=await port('query_snapshot',{capability:key(id),arguments:args});expect(response.status,JSON.stringify(response)).toBe('ready');return response.data;}
async function invoke(id:string,args:any){let result=await port('invoke',{capability:key(id),arguments:args,client_request_id:crypto.randomUUID(),preconditions:[]});for(let attempt=0;attempt<100&&!['succeeded','failed','cancelled','uncertain'].includes(result.status);attempt++){await new Promise(done=>setTimeout(done,40));result=await port('get_operation',{operation_id:result.operation.operation_id});}expect(result.status,result.error).toBe('succeeded');return result.output;}

test.beforeAll(async()=>{
 const annotationPackage=process.env.RHO_ANNOTATION_PLUGIN_PACKAGE,filesArchive=process.env.RHO_FILES_PLUGIN_ARCHIVE;
 const filesPackage=process.env.RHO_FILES_PLUGIN_PACKAGE;
 if(!annotationPackage||(!filesArchive&&!filesPackage))throw Error('Set RHO_ANNOTATION_PLUGIN_PACKAGE and RHO_FILES_PLUGIN_ARCHIVE to built, retained packages.');
 directory=await mkdtemp(join(tmpdir(),'rho-annotation-ui-'));project=join(directory,'project');await mkdir(project);project=await realpath(project);core=digest(await readFile(binary));
 await writeFile(join(project,'analysis.R'),'x <- 1\nprint(42)\n');execFileSync('git',['init','-q',project]);
 const database=join(directory,'state.sqlite');
 const filesImported=JSON.parse(execFileSync(binary,['--database',database,'plugins',filesPackage?'snapshot':'import',resolve(filesPackage??filesArchive!),...(filesPackage?['--target','aarch64-apple-darwin']:[])],{encoding:'utf8'})).result;
 const capturePackage=buildCaptureSource(directory);const captureSnapshot=JSON.parse(execFileSync(binary,['--database',database,'plugins','snapshot',capturePackage,'--target','aarch64-apple-darwin'],{encoding:'utf8'})).result;
 const agentPackage=process.env.RHO_AGENT_PLUGIN_PACKAGE;if(!agentPackage)throw Error('Supply a current Agent package for annotation draft acceptance.');
 const agentSnapshot=JSON.parse(execFileSync(binary,['--database',database,'plugins','snapshot',agentPackage,'--target','aarch64-apple-darwin'],{encoding:'utf8'})).result;
 const notesSnapshot=JSON.parse(execFileSync(binary,['--database',database,'plugins','snapshot',resolve(annotationPackage),'--target','aarch64-apple-darwin'],{encoding:'utf8'})).result;
 host=spawn(binary,['--database',database,'--project',project,'workbench'],{stdio:['ignore','pipe','pipe']});
 url=new URL(await new Promise<string>((done,reject)=>{let out='',errors='';const timer=setTimeout(()=>reject(Error(`Host startup timed out: ${errors}`)),30000);host.stderr!.on('data',b=>errors+=b);host.stdout!.on('data',b=>{out+=b;const found=out.match(/http:\/\/127\.0\.0\.1:\d+\/\?plugin-window#token=[a-z0-9]+/);if(found){clearTimeout(timer);done(found[0]);}});host.once('exit',code=>{clearTimeout(timer);reject(Error(`Host exited ${code}: ${errors}`));});}));
 const inspected=await query('plugins.inspect',{revision:filesImported.revision});
 files=(await invoke('plugins.activate',{revision:filesImported.revision,artifact:inspected.artifacts[0].id,target:'aarch64-apple-darwin',alias:'files',configuration:{},optional_capabilities:[]})).instance.identity;
 annotation=(await invoke('plugins.activate',{revision:notesSnapshot.revision,artifact:notesSnapshot.artifacts[0],target:'aarch64-apple-darwin',alias:'annotations',configuration:{},optional_capabilities:['plugins.instances','plugins.resolve','workspace.paths','files.read_text','files.context.preview','files.context.search','operation.get','operation.list_recent','resources.read','annotations.capture.read','annotations.capture.import','annotations.context.preview','windows.layout','windows.open_view','windows.update_layout'].map(key)})).instance.identity;
 captureOwner=(await invoke('plugins.activate',{revision:captureSnapshot.revision,artifact:captureSnapshot.artifacts[0],target:'aarch64-apple-darwin',alias:'capture-resource',configuration:{}})).instance.identity;
 agent=(await invoke('plugins.activate',{revision:agentSnapshot.revision,artifact:agentSnapshot.artifacts[0],target:'aarch64-apple-darwin',alias:'agent',configuration:{},optional_capabilities:['plugins.instances','plugins.inspect','annotations.context.search','annotations.context.preview','resources.read','operation.get'].map(key)})).instance.identity;
 view=(await invoke('windows.open_view',{expected_layout_version:0,group:null,view:{instance:annotation,window:windowId,contribution:'annotations',configuration:{},state:{}}})).view;
});
test.afterAll(async()=>{if(host?.exitCode===null){host.kill('SIGINT');await new Promise<void>(done=>host.once('exit',()=>done()));}if(directory&&completed)await rm(directory,{recursive:true,force:true});else if(directory)console.error(`Annotation UI fixture retained at ${directory}`);});

test('captures quoted Files evidence, recovers a lost note acknowledgement, and edits by revision',async({page},info)=>{
 page.on('dialog',dialog=>dialog.accept());let lost=false;const requests:any[]=[];
 await page.route('**/api/plugin-view',async route=>{const message=route.request().postDataJSON()?.message,body=message?.body;requests.push(message);if(!lost&&body?.type==='invoke'&&body.capability.id==='annotations.write'&&body.arguments?.arguments?.command?.kind==='create'){lost=true;const reply=await route.fetch();const response=await reply.json();expect(response.ok,response.error).toBe(true);await route.fulfill({response:reply,json:{...response,ok:false,error:'Fixture lost the note acknowledgement'}});}else await route.continue();});
 const address=new URL(url);address.searchParams.set('window',windowId);await page.goto(address.href);
 const frame=page.locator(`[data-plugin-frame="${view.view}"]`).frameLocator('iframe');
 await expect(frame.locator('#provider')).toContainText('files');await frame.locator('#provider').selectOption(files.instance);
 await frame.getByLabel('Project file').fill('analysis.R');await frame.getByRole('button',{name:'Read file'}).click();
 await expect(frame.locator('#source-text')).toHaveValue(/x <- 1/);
 await frame.locator('#source-text').evaluate((element:HTMLTextAreaElement)=>{const start=element.value.indexOf('x <- 1');element.setSelectionRange(start,start+6);});
 await frame.locator('#capture-selection').click();await expect(frame.locator('#evidence-status')).toContainText('Frozen evidence');await expect(frame.locator('#frozen-text')).toHaveText('x <- 1');
 await frame.getByLabel('Note',{exact:true}).fill('Check the original result');await frame.getByRole('button',{name:'Save note'}).click();
 await expect(frame.locator('#pending')).toBeVisible();await expect(frame.locator('#notice')).toContainText('lost the note acknowledgement');
 expect(requests.filter(r=>r?.body?.type==='invoke'&&r.body.arguments?.arguments?.command?.kind==='create')).toHaveLength(1);
 await page.reload();await expect(frame.locator('#pending')).toBeVisible();await expect(frame.getByLabel('Note',{exact:true})).toHaveValue('Check the original result');
 await frame.getByRole('button',{name:'Inspect original operation'}).click();await expect(frame.locator('#pending')).toBeHidden();await expect(frame.locator('#editor-title')).toContainText('Edit revision 1');
 const saved=(await query('views.inspect',{view:view.view})).state;expect(saved.pending).toBe(null);expect(saved.selected.revision).toBe(1);
 const note=await query('annotations.read',{binding:await query('plugins.resolve',{instance:annotation,capability:key('annotations.read')}),arguments:{kind:'read',annotation:saved.selected}});
 expect(note.evidence.fragment.text).toBe('x <- 1');expect(note.revision.note).toBe('Check the original result');
 await frame.getByLabel('Note',{exact:true}).fill('Revised after reviewing the result');await frame.getByRole('button',{name:'Save note'}).click();
 await expect(frame.locator('#editor-title')).toContainText('Edit revision 2');
 const updated=(await query('views.inspect',{view:view.view})).state;expect(updated.selected.revision).toBe(2);
 expect(requests.filter(r=>r?.body?.type==='invoke'&&r.body.arguments?.arguments?.command?.kind==='create')).toHaveLength(1);
 expect(digest(await readFile(binary))).toBe(core);expect(lost).toBe(true);
 await expect(frame.locator('#frozen-text')).toHaveText('x <- 1');
 await page.screenshot({path:info.outputPath('annotation-ui.png')});
 await page.setViewportSize({width:1920,height:900});await page.reload();await expect(frame.locator('#editor-title')).toContainText('Edit revision 2');await page.screenshot({path:info.outputPath('annotation-ui-wide.png')});
 await page.setViewportSize({width:390,height:844});await page.reload();await expect(frame.locator('#editor-title')).toContainText('Edit revision 2');const widths=await frame.locator('body').evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,inner:window.innerWidth,body:document.body.scrollWidth}));expect(widths.scroll,JSON.stringify(widths)).toBeLessThanOrEqual(widths.client+1);await page.screenshot({path:info.outputPath('annotation-ui-narrow.png')});await frame.locator('#editor-title').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('annotation-ui-narrow-editor.png')});
 const writeBinding=await query('plugins.resolve',{instance:annotation,capability:key('annotations.write')});
 let concurrent=await port('invoke',{capability:key('annotations.write'),arguments:{binding:writeBinding,arguments:{request_id:crypto.randomUUID(),command:{kind:'update',expected:updated.selected,note:'Parallel revision',labels:[],marks:[]}},preconditions:null},client_request_id:crypto.randomUUID(),preconditions:[]});
 for(let attempt=0;attempt<60&&!['succeeded','failed','cancelled','uncertain'].includes(concurrent.status);attempt++){await new Promise(done=>setTimeout(done,50));concurrent=await query('operation.get',{operation_id:concurrent.operation.operation_id}).then(data=>data.record);}
 expect(concurrent.status,concurrent.error).toBe('succeeded');expect(concurrent.output.outcome.annotation.revision).toBe(3);
 await frame.getByLabel('Note',{exact:true}).fill('My stale edit must be retained');await frame.getByRole('button',{name:'Save note'}).click();await expect(frame.locator('#conflict')).toBeVisible();await expect(frame.locator('#pending')).toBeHidden();await expect(frame.getByLabel('Note',{exact:true})).toHaveValue('My stale edit must be retained');
 await frame.getByRole('button',{name:'Refresh notes'}).click();await frame.getByRole('button',{name:/Parallel revision/}).click();await frame.getByRole('button',{name:'Replace draft',exact:true}).click();await expect(frame.locator('#editor-title')).toContainText('Edit revision 3');
 await frame.getByRole('button',{name:'Delete note'}).click();await expect(frame.getByRole('dialog',{name:'Delete this note?'})).toBeVisible();await frame.getByRole('button',{name:'Keep note'}).click();await expect(frame.locator('#notes')).toContainText('Parallel revision');await frame.getByRole('button',{name:'Delete note'}).click();await frame.getByRole('button',{name:'Delete permanently'}).click();await expect(frame.locator('#notes')).toContainText('No saved notes');
 const historical=await query('annotations.read',{binding:await query('plugins.resolve',{instance:annotation,capability:key('annotations.read')}),arguments:{kind:'read',annotation:updated.selected}});expect(historical.revision.note).toBe('Revised after reviewing the result');
 await writeFile(info.outputPath('result.json'),JSON.stringify({core_sha256:core,files,annotation,view:view.view,revision:updated.selected,checks:['Exact Files preview selected and frozen before note entry','One create Operation despite lost acknowledgement and reload','Original Operation recovered without replay','Existing note edited with exact revision CAS','Concurrent update refuses stale edit and preserves draft','Explicit tombstone leaves historical revision readable','Normal, wide and narrow screenshots inspected; no horizontal overflow','Core binary unchanged']},null,2)+'\n');completed=true;
});

function sourceGroup(node:any,viewId:string):string|null{return node.kind==='tabs'?node.views.includes(viewId)?node.id:null:node.kind==='split'?node.children.map((child:any)=>sourceGroup(child,viewId)).find(Boolean)??null:null;}
async function plugin(instance:any,id:string,args:any){return query(id,{binding:await query('plugins.resolve',{instance,capability:key(id)}),arguments:args,preconditions:null});}
async function pluginWrite(instance:any,id:string,args:any){return invoke(id,{binding:await query('plugins.resolve',{instance,capability:key(id)}),arguments:args,preconditions:null});}

test('draws on retained images, confirms deletion, and opens exact component notes and Agent draft',async({page},info)=>{
 completed=false;page.on('dialog',dialog=>dialog.accept());const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const nativeRoot=(await query('workspace.paths',{})).project_root;
 await writeFile(join(project,'unrelated.R'),'A separate source\n');const otherFile=await query('files.read_text',{binding:{...(await query('plugins.resolve',{instance:files,capability:key('files.read_text')})),target:nativeRoot},arguments:{path:'unrelated.R',start_line:1,limit_lines:1},preconditions:null});const otherReference={provider:files,contribution:'files',window:windowId,selector:otherFile.file};const otherEvidence=(await pluginWrite(annotation,'annotations.write',{request_id:crypto.randomUUID(),command:{kind:'freeze',reference:otherReference,inclusion:{kind:'text'},anchor:{kind:'whole_item'}}})).outcome.evidence_id;await pluginWrite(annotation,'annotations.write',{request_id:crypto.randomUUID(),command:{kind:'create',evidence_id:otherEvidence,note:'Unrelated source note',labels:[],marks:[],continued_from:null}});

 const file=await query('files.read_text',{binding:{...(await query('plugins.resolve',{instance:files,capability:key('files.read_text')})),target:nativeRoot},arguments:{path:'analysis.R',start_line:1,limit_lines:1},preconditions:null});
 const reference={provider:files,contribution:'files',window:windowId,selector:file.file};
 const resource=(await plugin(captureOwner,'fixture.capture.resource',{damaged:false})).reference;
 const capture=(await pluginWrite(annotation,'annotations.capture.import',{request_id:crypto.randomUUID(),reference:resource})).outcome.capture;
 const frozen=(await pluginWrite(annotation,'annotations.write',{request_id:crypto.randomUUID(),command:{kind:'freeze',reference,inclusion:{kind:'text'},anchor:{kind:'captured_view',capture}}})).outcome.evidence_id;
 const imageNote=(await pluginWrite(annotation,'annotations.write',{request_id:crypto.randomUUID(),command:{kind:'create',evidence_id:frozen,note:'Review captured PNG',labels:['Question'],marks:[],continued_from:null}})).outcome.annotation;
 const address=new URL(url);address.searchParams.set('window',windowId);await page.goto(address.href);const frame=page.locator(`[data-plugin-frame="${view.view}"]`).frameLocator('iframe');
 await frame.getByRole('button',{name:/Review captured PNG/}).click();await expect(frame.locator('#capture-image')).toBeVisible();await expect(frame.locator('#capture-image')).toHaveJSProperty('naturalWidth',256);
 await frame.getByRole('button',{name:'Rectangle',exact:true}).click();const bounds=await frame.locator('#mark-canvas').boundingBox();expect(bounds).not.toBeNull();
 await page.mouse.move(bounds!.x+bounds!.width*.1,bounds!.y+bounds!.height*.2);await page.mouse.down();await page.mouse.move(bounds!.x+bounds!.width*.5,bounds!.y+bounds!.height*.6);await page.mouse.up();await expect(frame.locator('#mark-list')).toContainText('1. rectangle');
 await frame.getByLabel('Text mark').fill('Check this region');await frame.getByRole('button',{name:'Text',exact:true}).click();await page.mouse.click(bounds!.x+bounds!.width*.25,bounds!.y+bounds!.height*.3);await expect(frame.locator('#mark-list')).toContainText('2. text');
 await frame.getByRole('button',{name:'Undo mark'}).click();await expect(frame.locator('#mark-list')).not.toContainText('text');
 await frame.getByLabel('Note',{exact:true}).fill('Review captured PNG · marked region');await frame.getByRole('button',{name:'Save note'}).click();await expect(frame.locator('#editor-title')).toContainText('revision 2');
 const stored=await plugin(annotation,'annotations.read',{kind:'read',annotation:{...imageNote,revision:2}});expect(stored.revision.marks).toHaveLength(1);expect(stored.revision.marks[0].x).toBeCloseTo(.1,2);expect(stored.revision.marks[0].width).toBeCloseTo(.4,2);
 await page.setViewportSize({width:390,height:844});await page.reload();await expect(frame.locator('#mark-list')).toContainText('1. rectangle');await expect(frame.getByRole('button',{name:'Rectangle',exact:true})).toBeEnabled();await expect(frame.locator('#capture-image')).toHaveJSProperty('naturalWidth',256);await frame.locator('#capture-frame').evaluate(element=>element.scrollIntoView({block:'center'}));await expect.poll(async()=>{const b=await frame.locator('#capture-frame').boundingBox();return !!b&&b.y>=38&&b.y+b.height<=844;}).toBe(true);await page.screenshot({path:info.outputPath('image-narrow.png')});
 expect((await plugin(annotation,'annotations.read',{kind:'read',annotation:{...imageNote,revision:2}})).revision.marks).toEqual(stored.revision.marks);
 await frame.getByRole('button',{name:'Open capture',exact:true}).click();await expect(frame.getByRole('dialog',{name:'Full captured view'})).toBeVisible();await frame.getByRole('button',{name:'Close capture'}).click();
 await page.setViewportSize({width:1440,height:900});await page.reload();await expect(frame.locator('#capture-image')).toBeVisible();await expect(frame.getByRole('button',{name:'Rectangle',exact:true})).toBeEnabled();await expect(frame.locator('#capture-image')).toHaveJSProperty('naturalWidth',256);await frame.locator('#annotation-editor').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('image-normal.png')});
 // The component launcher persists its original open before dispatch. Lose only its acknowledgement.
 let lost=false,opens=0;
 await page.route('**/api/plugin-view',async route=>{const message=route.request().postDataJSON()?.message,body=message?.body;if(body?.type==='invoke'&&body.capability.id==='windows.open_view'&&body.arguments.view?.contribution==='annotations'){opens++;if(!lost){lost=true;const response=await route.fetch();const reply=await response.json();await route.fulfill({response,json:{...reply,ok:false,error:'Fixture lost annotation open acknowledgement'}});return;}}await route.continue();});
 let layout=await query('windows.layout',{window:windowId});fileView=(await invoke('windows.open_view',{expected_layout_version:layout.version,group:sourceGroup(layout.layout,view.view),view:{instance:files,window:windowId,contribution:'files',configuration:{editor:null,editor_group:null,runtime:null},state:{}}})).view;
 await page.reload();const source=page.locator(`[data-plugin-frame="${fileView.view}"]`).frameLocator('iframe');await source.getByRole('button',{name:/analysis\.R/}).click();await source.getByRole('button',{name:'Annotate',exact:true}).click();
 const chooser=source.getByRole('dialog',{name:'Annotate this input'});await expect(chooser.locator('[data-annotation=preview]')).toContainText('x <- 1');await chooser.getByRole('button',{name:'Open notes',exact:true}).click();
 await expect.poll(async()=>!!(await query('views.inspect',{view:fileView.view})).state.agent?.annotation?.pending).toBe(true);expect(opens).toBe(1);
 // Select the retained source tab after the Host placed the new notes view.
 layout=await query('windows.layout',{window:windowId});const selectSource=(node:any):any=>node.kind==='tabs'&&node.views.includes(fileView.view)?{...node,selected:fileView.view}:node.kind==='split'?{...node,children:node.children.map(selectSource)}:node;
 await invoke('windows.update_layout',{window:windowId,expected_version:layout.version,layout:selectSource(layout.layout)});await page.reload();await source.getByRole('button',{name:'Annotate',exact:true}).click();await chooser.getByRole('button',{name:'Inspect original operation',exact:true}).click();
 await expect.poll(async()=>(await query('views.inspect',{view:fileView.view})).state.agent?.annotation?.pending).toBe(null);const retainedSource=(await query('views.inspect',{view:fileView.view})).state;const launched=retainedSource.agent.annotation.opened;expect(opens).toBe(1);expect(launched.configuration.source_request.source.reference.selector).toEqual(file.file);
 layout=await query('windows.layout',{window:windowId});const selectNotes=(node:any):any=>node.kind==='tabs'&&node.views.includes(launched.view)?{...node,selected:launched.view}:node.kind==='split'?{...node,children:node.children.map(selectNotes)}:node;
 await invoke('windows.update_layout',{window:windowId,expected_version:layout.version,layout:selectNotes(layout.layout)});await page.reload();const focused=page.locator(`[data-plugin-frame="${launched.view}"]`).frameLocator('iframe');
 await expect(focused.locator('#component-text')).toHaveValue(/x <- 1/);await focused.locator('#capture-component-whole').click();await expect(focused.locator('#evidence-status')).toContainText('Frozen evidence');await focused.getByLabel('Note',{exact:true}).fill('Component note 中文');await focused.getByRole('button',{name:'Save note',exact:true}).click();await expect(focused.locator('#editor-title')).toContainText('revision 1');
 const componentNote=(await query('views.inspect',{view:launched.view})).state.selected;
 await expect(focused.getByRole('button',{name:'Save note',exact:true})).toBeEnabled();for(const width of [600,320]){await page.setViewportSize({width,height:900});await focused.locator('#annotation-editor').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`component-${width}.png`)});expect(await focused.locator('body').evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);}await page.setViewportSize({width:1440,height:900});
 await focused.getByRole('button',{name:'Back to source',exact:true}).click();await expect(source.getByRole('button',{name:/analysis\.R/})).toBeVisible();await expect.poll(async()=>(await query('views.inspect',{view:launched.view})).state.pending).toBe(null);expect((await query('views.inspect',{view:fileView.view})).state).toEqual(retainedSource);
 // Select the two exact revisions, preview them, and append to an existing editable draft.
 layout=await query('windows.layout',{window:windowId});await invoke('windows.update_layout',{window:windowId,expected_version:layout.version,layout:selectNotes(layout.layout)});await page.reload();
 await expect(focused.locator('#notes')).toContainText('Component note 中文');await expect(focused.locator('#notes')).not.toContainText('Unrelated source note');await expect(focused.getByRole('checkbox',{name:'Select visible notes'})).toBeEnabled();await focused.getByRole('checkbox',{name:'Select visible notes'}).check();await expect.poll(async()=>(await query('views.inspect',{view:launched.view})).state.checked.length).toBe(2);await focused.getByRole('button',{name:'Add to Agent',exact:true}).click();await expect(focused.locator('#agent-preview')).toContainText('Component note 中文');await expect(focused.locator('#agent-preview')).toContainText('Review captured PNG');await focused.getByLabel('Agent instance',{exact:true}).selectOption(agent.instance);await focused.getByRole('button',{name:'Open Agent',exact:true}).click();
 const notesState=(await query('views.inspect',{view:launched.view})).state;await expect.poll(async()=>!!(await query('views.inspect',{view:launched.view})).state.agentOpened).toBe(true);const opened=(await query('views.inspect',{view:launched.view})).state.agentOpened;
 expect(opened.configuration.component_request.sources.map((entry:any)=>entry.reference.selector)).toEqual(expect.arrayContaining([componentNote,{...imageNote,revision:2}]));
 const task='annotation-existing-draft';let conversation=await pluginWrite(agent,'agent.model.create',{conversation_id:task,profile:'project'});conversation=await pluginWrite(agent,'agent.model.draft',{conversation_id:task,draft_version:conversation.draft_version,content:{text:'Existing draft 中文',context:[],assets:[]},grant:null});
 await page.reload();const agentFrame=page.locator(`[data-plugin-frame="${opened.view}"]`).frameLocator('iframe');await agentFrame.getByLabel('Select task',{exact:true}).selectOption(`rho:${task}`);await expect(agentFrame.getByLabel('Agent message',{exact:true})).toHaveValue('Existing draft 中文');
 // The fixture created the task outside this view; use the existing explicit control transition.
 await agentFrame.getByRole('button',{name:'Take over',exact:true}).click();await expect(agentFrame.getByLabel('Agent message',{exact:true})).toBeEditable();await agentFrame.locator('#component-request').evaluate(element=>{(element as HTMLDetailsElement).open=true;});await agentFrame.getByRole('button',{name:'Add context to draft',exact:true}).click();
 await expect.poll(async()=>(await plugin(agent,'agent.model.conversation',{conversation_id:task})).draft_content.context.length).toBe(2);conversation=await plugin(agent,'agent.model.conversation',{conversation_id:task});expect(conversation.draft_content.text).toBe('Existing draft 中文');expect(conversation.draft_content.context.map((entry:any)=>entry.reference.selector)).toEqual(expect.arrayContaining([componentNote,{...imageNote,revision:2}]));await page.reload();expect((await plugin(agent,'agent.model.conversation',{conversation_id:task})).draft_content).toEqual(conversation.draft_content);
 // A new owner content version has a separate note; history stays on the same source lineage.
 layout=await query('windows.layout',{window:windowId});await invoke('windows.update_layout',{window:windowId,expected_version:layout.version,layout:selectNotes(layout.layout)});await page.reload();await focused.getByRole('button',{name:/Component note 中文/}).click();
 await writeFile(join(project,'analysis.R'),'x <- 2\nprint(84)\n');await query('files.read_text',{binding:{...(await query('plugins.resolve',{instance:files,capability:key('files.read_text')})),target:nativeRoot},arguments:{path:'analysis.R',start_line:1,limit_lines:1},preconditions:null});
 await focused.getByRole('button',{name:'Continue on new version',exact:true}).click();await expect(focused.locator('#component-item')).toContainText('analysis.R');await focused.locator('#component-item').selectOption({label:'analysis.R'});await focused.locator('#component-inclusion').selectOption({label:'Text (up to 16 KiB)'});await focused.getByRole('button',{name:'Preview',exact:true}).click();await expect(focused.locator('#component-text')).toHaveValue(/x <- 2/);await focused.locator('#capture-component-whole').click();await expect(focused.locator('#evidence-status')).toContainText('Frozen evidence');await focused.getByLabel('Note',{exact:true}).fill('Continued on version two');await focused.getByRole('button',{name:'Save note',exact:true}).click();await expect(focused.locator('#editor-title')).toContainText('revision 1');const continued=(await query('views.inspect',{view:launched.view})).state.selected;expect((await plugin(annotation,'annotations.read',{kind:'read',annotation:continued})).revision.continued_from).toEqual(componentNote);
 await focused.locator('#note-filter').selectOption('version');await expect(focused.locator('#notes')).toContainText('Continued on version two');await expect(focused.locator('#notes')).not.toContainText('Review captured PNG');await expect(focused.locator('#notes')).not.toContainText('Unrelated source note');await focused.locator('#note-filter').selectOption('history');await expect(focused.locator('#notes')).toContainText('Component note 中文');await expect(focused.locator('#notes')).toContainText('Review captured PNG');await expect(focused.locator('#notes')).not.toContainText('Continued on version two');await expect(focused.locator('#notes')).not.toContainText('Unrelated source note');await page.reload();await expect(focused.locator('#notes')).toContainText('Component note 中文');expect((await plugin(annotation,'annotations.read',{kind:'read',annotation:{...imageNote,revision:2}})).revision.marks).toEqual(stored.revision.marks);expect((await plugin(agent,'agent.model.conversation',{conversation_id:task})).draft_content).toEqual(conversation.draft_content);
 expect(errors).toEqual([]);expect(digest(await readFile(binary))).toBe(core);
 await writeFile(info.outputPath('result.json'),JSON.stringify({core_sha256:core,annotation,files,agent,component_note:componentNote,image_note:{...imageNote,revision:2},capture,marks:stored.revision.marks,source_view:fileView.view,annotation_view:launched.view,agent_view:opened.view,original_open_count:opens,task,sent:false,source_state_preserved:true,source_scoped_history:true,continued,draft:conversation.draft_content,limits:'PNG from deterministic public resource fixture; not a real scientific plot or OS IME test.'},null,2)+'\n');completed=true;
});
