import {test,expect} from '@playwright/test';
import {spawn,execFileSync} from 'node:child_process';
import {mkdtemp,mkdir,rm,realpath,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {buildStudioPlugin} from '../../scripts/build-studio-plugin.mjs';
import {buildUiFixture} from '../../scripts/fixtures/plugin-ui.mjs';
let directory:string,project:string,url:URL,host:ReturnType<typeof spawn>,completed=false,studioView:any,oldView:any,otherView:any,old:any,newer:any,initial:any;
const windowId='studio-scene-window';
async function port(method:string,params:any,window=windowId){const reply=await fetch(new URL('/api/host',url),{method:'POST',headers:{Authorization:`Bearer ${url.hash.slice(7)}`,'Content-Type':'application/json','X-Rho-Studio-Window':window},body:JSON.stringify({project_root:project,frame:{id:crypto.randomUUID(),request:{method,params}}})}).then(r=>r.json());if(!reply.ok)throw Error(reply.error);return reply.result;}
async function query(id:string,args:any,window=windowId){return(await port('query_snapshot',{capability:{id,version:1},arguments:args},window)).data;}
async function invoke(id:string,args:any,window=windowId){const result=await port('invoke',{capability:{id,version:1},arguments:args,preconditions:[],client_request_id:crypto.randomUUID()},window);expect(result.status,result.error).toBe('succeeded');return result.output;}
test.beforeAll(async()=>{
 directory=await mkdtemp(join(tmpdir(),'rho-studio-scene-browser-'));project=join(directory,'analysis');await mkdir(project);project=await realpath(project);
 const database=join(directory,'state.sqlite'),binary=resolve('../target/debug/rho');
 const snapshot=(path:string)=>JSON.parse(execFileSync(binary,['--database',database,'plugins','snapshot',path,'--target','ui-web'],{encoding:'utf8'})).result;
 const studio=snapshot(buildStudioPlugin(join(directory,'studio'))),subjectPath=buildUiFixture(directory);
 const manifest=JSON.parse(await readFile(join(subjectPath,'plugin.json'),'utf8'));manifest.requires=manifest.requires.filter((r:any)=>r.capability.id!=='fixture.answer');manifest.name='Scenario report';manifest.version='1.0';await writeFile(join(subjectPath,'plugin.json'),JSON.stringify(manifest,null,2));old=snapshot(subjectPath);
 manifest.version='2.0';await writeFile(join(subjectPath,'plugin.json'),JSON.stringify(manifest,null,2));await writeFile(join(subjectPath,'src/index.html'),(await readFile(join(subjectPath,'src/index.html'),'utf8')).replace('<h1>Independent View</h1>','<h1>Revised report</h1>'));execFileSync(process.execPath,[join(subjectPath,'build.mjs')],{cwd:subjectPath});newer=snapshot(subjectPath);
 host=spawn(binary,['--database',database,'--project',project,'--plugins-only','workbench'],{stdio:['ignore','pipe','pipe']});
 url=new URL(await new Promise<string>((done,reject)=>{let out='',errors='';const timer=setTimeout(()=>reject(Error(`Host startup timed out: ${errors}`)),40000);host.stderr!.on('data',b=>errors+=b);host.stdout!.on('data',b=>{out+=b;const found=out.match(/http:\/\/127\.0\.0\.1:\d+\/\?plugin-window#token=[a-z0-9]+/);if(found){clearTimeout(timer);done(found[0]);}});host.once('exit',code=>{clearTimeout(timer);reject(Error(`Host exited ${code}: ${errors}`));});}));
 const studioInstance=(await invoke('plugins.activate',{revision:studio.revision,artifact:studio.artifacts[0],target:'ui-web',alias:'studio',configuration:{}})).instance.identity;
 const report=(await invoke('plugins.activate',{revision:old.revision,artifact:old.artifacts[0],target:'ui-web',alias:'report',configuration:{}})).instance.identity;
 studioView=await invoke('views.open',{instance:studioInstance,window:windowId,contribution:'studio',configuration:{},state:{}});
 oldView=await invoke('views.open',{instance:report,window:windowId,contribution:'view',configuration:{},state:{text:'Old checkpoint'}});
 initial=await invoke('scenarios.checkpoint',{scenario:'report-comparison',expected_head:null,name:'Report comparison',instances:{studio:{plugin:studioInstance.plugin,revision:studioInstance.revision,artifact:studioInstance.artifact,configuration:{},dependencies:{}},report:{plugin:report.plugin,revision:report.revision,artifact:report.artifact,configuration:{},dependencies:{}}},providers:[],layout:{kind:'tabs',id:'report-tabs',selected:'studio-view',views:[{id:'studio-view',instance:'studio',contribution:'studio',configuration:{},state:{},state_revision:studio.revision,resource:null},{id:'report-view',instance:'report',contribution:'view',configuration:{},state:{text:'Old checkpoint'},state_revision:old.revision,resource:null}]}});
 await invoke('scenarios.apply',{window:windowId,revision:initial.id,expected_layout_version:0,instances:{studio:studioInstance,report},views:{'studio-view':studioView.view,'report-view':oldView.view}});
 otherView=(await invoke('windows.open_view',{expected_layout_version:0,group:null,view:{instance:report,window:'other-window',contribution:'view',configuration:{},state:{text:'Other window'}}},'other-window')).view;
});
test.afterAll(async()=>{if(host?.exitCode===null){host.kill('SIGINT');await new Promise<void>(done=>host.once('exit',()=>done()));}if(directory&&completed)await rm(directory,{recursive:true,force:true});else if(directory)console.error(`Studio scenario fixture retained at ${directory}`);});
test('Studio applies exact checkpoints and restores historical live views without replay',async({page,context},info)=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const address=new URL(url);address.searchParams.set('window','other-window');const other=await context.newPage();await other.goto(address.href);const otherFrame=other.locator(`[data-plugin-frame="${otherView.view}"]`).frameLocator('iframe');await expect(otherFrame.getByLabel('View note',{exact:true})).toHaveValue('Other window');await otherFrame.getByLabel('View note',{exact:true}).fill('Other unsaved analysis 中文 Ω');await expect(otherFrame.getByLabel('View note',{exact:true})).toHaveValue('Other unsaved analysis 中文 Ω');
 address.searchParams.set('window',windowId);await page.goto(address.href);await page.bringToFront();const region=page.locator(`[data-plugin-frame="${studioView.view}"]`),frame=region.frameLocator('iframe');
 await frame.getByRole('button',{name:'Choose revision',exact:true}).click();await frame.getByRole('button',{name:/Scenario report · 2.0/}).click();await frame.locator('#close-chooser').click();
 await frame.getByRole('button',{name:'Apply to scenario',exact:true}).click();await frame.getByLabel('Target scenario',{exact:true}).selectOption(initial.id);await expect(frame.getByLabel('Instance alias',{exact:true})).toHaveValue('report');await expect(frame.getByRole('button',{name:'Stage selected build',exact:true})).toBeDisabled();
 await frame.getByRole('button',{name:'Preview',exact:true}).click();await frame.getByText('Preview configuration and fixture data',{exact:true}).click();await frame.getByLabel('Initial view state',{exact:true}).fill('{"text":"New preview"}');await frame.getByRole('button',{name:'Start preview',exact:true}).click();await expect(page.locator('[data-plugin-preview=fixture]')).toBeVisible();
 await page.getByRole('tab',{name:'Plugin Studio',exact:true}).click();await frame.getByRole('button',{name:'Close preview view',exact:true}).click();await expect(frame.locator('#preview-instance')).toContainText('view closed');await frame.locator('#release-preview').click();await frame.locator('#close-development').click();
 await frame.getByRole('button',{name:'Apply to scenario',exact:true}).click();await frame.getByLabel('New view state by view ID',{exact:true}).fill('{"report-view":{"text":"New scenario state"}}');await frame.getByRole('button',{name:'Stage selected build',exact:true}).click();await expect(frame.locator('#scenario-proposal')).toContainText(newer.revision);
 let lost=false;await page.route('**/api/plugin-view',async route=>{const body=route.request().postDataJSON()?.message?.body;if(!lost&&body?.type==='invoke'&&body.capability.id==='scenarios.checkpoint'){lost=true;const response=await route.fetch(),reply=await response.json();expect(reply.ok).toBe(true);await route.fulfill({response,json:{id:reply.id,ok:false,error:'Fixture lost committed scenario acknowledgement'}});}else await route.continue();});
 await frame.getByRole('button',{name:'Save scenario checkpoint',exact:true}).click();await expect(frame.locator('#scenario-pending')).toBeVisible();const newHead=(await query('scenarios.list',{after:null,limit:20})).scenarios[0].revision;expect(newHead).not.toBe(initial.id);expect((await query('windows.scenario',{window:windowId})).scenario.revision).toBe(initial.id);
 await page.reload();await frame.getByRole('button',{name:'Apply to scenario',exact:true}).click();await frame.getByRole('button',{name:'Inspect original scenario request',exact:true}).click();await expect(frame.locator('#scenario-pending')).toBeHidden();await page.unroute('**/api/plugin-view');expect((await query('scenarios.list',{after:null,limit:20})).scenarios[0].revision).toBe(newHead);
 await frame.locator('#close-scenario').click();await page.getByRole('tab',{name:'Independent View',exact:true}).click();const oldFrame=page.locator(`[data-plugin-frame="${oldView.view}"]`).frameLocator('iframe');await oldFrame.getByLabel('View note',{exact:true}).fill('Unsaved old report 中文 Ω');await page.getByRole('tab',{name:'Plugin Studio',exact:true}).click();await frame.getByRole('button',{name:'Apply to scenario',exact:true}).click();
 await frame.getByRole('button',{name:'Prepare instances',exact:true}).click();await expect(frame.locator('#scenario-lifecycle')).toContainText('ready to apply');expect((await query('windows.scenario',{window:windowId})).scenario.revision).toBe(initial.id);
 for(const width of [1440,1920,390,220]){await page.setViewportSize({width,height:1000});await expect.poll(async()=>Math.abs(await frame.locator('body').evaluate(()=>innerWidth)-width)).toBeLessThan(5);await frame.locator('#scenario-dialog').evaluate(dialog=>dialog.scrollTop=0);await frame.locator('body').evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));expect(await frame.locator('body').evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:info.outputPath(`studio-scenario-${width}.png`)});if(width<=390){await frame.getByRole('button',{name:'Back to scenarios',exact:true}).click();await expect(frame.getByLabel('Target scenario',{exact:true})).toBeFocused();await expect(frame.locator('#scenario-comparison')).toBeHidden();await page.screenshot({path:info.outputPath(`studio-scenario-navigation-${width}.png`)});await frame.locator('#scenario-history button').first().click();await frame.getByRole('button',{name:'Apply to this window',exact:true}).scrollIntoViewIfNeeded();await expect(frame.getByRole('button',{name:'Apply to this window',exact:true})).toBeInViewport();await page.screenshot({path:info.outputPath(`studio-scenario-controls-${width}.png`)});}}
 await page.setViewportSize({width:1440,height:1000});await frame.getByRole('button',{name:'Apply to this window',exact:true}).click();await expect(frame.locator('#scenario-applied')).toContainText(newHead.slice(7,15));
 const applied=await query('windows.scenario',{window:windowId});expect(applied.scenario.instances.report.revision).toBe(newer.revision);expect(applied.scenario.instances.report.instance).not.toBe(oldView.instance.instance);expect(applied.scenario.views['studio-view']).toBe(studioView.view);expect((await query('plugins.instance',{instance:oldView.instance})).instance.state).toBe('active');expect((await query('views.inspect',{view:oldView.view})).closed).toBe(false);
 await frame.locator('#close-scenario').click();await page.getByRole('tab',{name:'Independent View',exact:true}).click();const newFrame=page.locator(`[data-plugin-frame="${applied.scenario.views['report-view']}"]`).frameLocator('iframe');await expect(newFrame.getByRole('heading',{name:'Revised report',exact:true})).toBeVisible();await expect(newFrame.getByLabel('View note',{exact:true})).toHaveValue('New scenario state');await newFrame.getByLabel('View note',{exact:true}).fill('New version unsaved');
 await page.getByRole('tab',{name:'Plugin Studio',exact:true}).click();await frame.getByRole('button',{name:'Apply to scenario',exact:true}).click();await frame.locator(`#scenario-history [data-revision="${initial.id}"]`).click();await frame.getByRole('button',{name:'Restore as new checkpoint',exact:true}).click();await expect.poll(async()=>(await query('scenarios.list',{after:null,limit:20})).scenarios[0].revision).not.toBe(newHead);const restored=(await query('scenarios.list',{after:null,limit:20})).scenarios[0].revision;expect(restored).not.toBe(initial.id);expect((await query('scenarios.get',{revision:restored})).parent).toBe(newHead);expect((await query('windows.scenario',{window:windowId})).scenario.revision).toBe(newHead);
 await frame.getByRole('button',{name:'Prepare instances',exact:true}).click();await expect(frame.locator('#scenario-lifecycle')).toContainText('ready to apply');await frame.getByRole('button',{name:'Apply to this window',exact:true}).click();await expect(frame.locator('#scenario-applied')).toContainText(restored.slice(7,15));await frame.locator('#close-scenario').click();await page.getByRole('tab',{name:'Independent View',exact:true}).click();await expect(oldFrame.getByLabel('View note',{exact:true})).toHaveValue('Unsaved old report 中文 Ω');await expect(otherFrame.getByLabel('View note',{exact:true})).toHaveValue('Other unsaved analysis 中文 Ω');expect((await query('views.inspect',{view:applied.scenario.views['report-view']})).closed).toBe(false);expect((await query('plugins.instance',{instance:applied.scenario.instances.report})).instance.state).toBe('active');
 await page.bringToFront();await expect(oldFrame.getByRole('heading',{name:'Independent View',exact:true})).toBeVisible();await oldFrame.locator('body').evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));await page.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('studio-scenario-restored.png')});completed=true;
});
