import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
const reuse = process.argv.includes('--reuse-native');
assert.ok(process.argv.length <= 3 && process.argv.slice(2).every(arg => arg === '--reuse-native'), 'Usage: node build.mjs [--reuse-native]');
assert.ok(fs.existsSync(path.join(root, 'Cargo.toml')), 'Assemble a standalone Remote source package before building.');
if (!reuse) execFileSync(process.env.RHO_PLUGIN_CARGO ?? 'cargo', ['build', '--locked', '--offline', '-p', 'rho-remote-backend', '--bins'], {cwd: root, stdio: 'inherit'});
const target = process.env.CARGO_TARGET_DIR ? path.resolve(root, process.env.CARGO_TARGET_DIR) : path.join(root, 'target');
execFileSync(path.join(target, 'debug/export-remote-manifest'), [path.join(root, 'plugin.json')], {cwd: root, stdio: 'inherit'});
const walk = directory => fs.readdirSync(directory, {withFileTypes: true}).flatMap(entry => {
  assert.ok(!entry.isSymbolicLink(), 'Package sources must not contain symlinks');
  if (['target', 'dist', 'node_modules', '.git', '__pycache__'].includes(entry.name)) return [];
  const location = path.join(directory, entry.name);
  return entry.isDirectory() ? walk(location) : [path.relative(root, location).split(path.sep).join('/')];
});
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'plugin.json'), 'utf8'));
manifest.source.files = walk(root).filter(file => file !== 'plugin.json' && !manifest.source.lockfiles.includes(file)).sort();
fs.writeFileSync(path.join(root, 'plugin.json'), JSON.stringify(manifest, null, 2) + '\n');
fs.mkdirSync(path.join(root, 'dist'), {recursive: true});
fs.copyFileSync(path.join(target, 'debug/rho-remote-backend'), path.join(root, 'dist/rho-remote-backend'));
fs.chmodSync(path.join(root, 'dist/rho-remote-backend'), 0o755);
