// Runs from this Remote package, including a standalone source assembly.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),check=process.argv.includes('--check');
assert.ok(process.argv.slice(2).every(arg=>arg==='--check'),'Use no arguments to generate, or --check');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'rho-remote-protocol-'));
const files=(directory,prefix='')=>fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{
  const relative=path.join(prefix,entry.name);
  return entry.isDirectory()?files(path.join(directory,entry.name),relative):[relative];
}).sort();
function synchronize(file,text){
  if(check)assert.equal(fs.readFileSync(file,'utf8'),text,`Stale Remote protocol: ${file}`);
  else{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
}
try{
  execFileSync(process.env.RHO_PLUGIN_CARGO??'cargo',['run','--manifest-path',path.join(root,'api/Cargo.toml'),'-p','rho-remote-api','--bin','export-remote-plugin','--locked','--offline','--',temporary],{cwd:root,stdio:'inherit'});
  const sdk=path.join(root,'sdk');
  for(const section of ['types','schema']){
    const names=files(path.join(temporary,section));
    const targetNames=names.map(name=>section==='types'?name.replace(/\.ts$/,'.d.ts'):name);
    if(check)assert.deepEqual(files(path.join(sdk,section)),targetNames);
    for(const name of names){
      let text=fs.readFileSync(path.join(temporary,section,name),'utf8').replace(/[ \t]+$/gm,'');
      if(section==='types')text=text.replace(/(from\s+["'])(\.[^"']+)(["'])/g,(_m,start,spec,end)=>`${start}${spec}.js${end}`);
      synchronize(path.join(sdk,section,section==='types'?name.replace(/\.ts$/,'.d.ts'):name),text);
    }
    if(!check)for(const name of files(path.join(sdk,section)))if(!targetNames.includes(name)){
      assert.ok(section==='schema'||fs.readFileSync(path.join(sdk,section,name),'utf8').startsWith('// This file was generated by [ts-rs]'));
      fs.unlinkSync(path.join(sdk,section,name));
    }
  }
  synchronize(path.join(sdk,'index.d.ts'),files(path.join(temporary,'types')).map(name=>`export type * from "./types/${name.replace(/\.ts$/,'.js')}";`).join('\n')+'\n');
  console.log(`Remote public declarations and schemas ${check?'verified':'generated'}.`);
}finally{fs.rmSync(temporary,{recursive:true,force:true});}
